### ISSUE TITLE
Can't build test project targetting netcoreapp1.x

### ISSUE THREAD

**Issue by johlrich** [fable-compiler/Fable#1039]
### Description

After upgrading from 1.0.8 to 1.1.5, I am no longer able to setup a test project that can execute tests using both dotnet test and npm test.

### Repro code

Build a project that targets netcoreapp1.0 and references something targeting netstandard1.6 like Fable.Import.Browser with fable

### Expected and actual results

Expect `dotnet test` and `dotnet fable npm-test` to both work.

Actual: 

Fable appears to want search for netstandard1.0 libraries when using a netcoreapp1.0 target.

The output with exception is: 
```
Bundling for development...
ERROR: Cannot match target netstandard1.0 for library Fable.Import.Browser
   at Fable.Tools.ProjectCracker.tryGetPaketRef@72-4.Invoke(String message)
   at Microsoft.FSharp.Core.OptionModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpOption`1 option)
   at Microsoft.FSharp.Collections.IEnumerator.choose@205.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Fable.Tools.ProjectCracker.crackProjects@323(TargetFramework targetFramework, FSharpOption`1 paketDir, FSharpList`1 acc, String projFile)
   at Microsoft.FSharp.Collections.SeqModule.FoldBack[T,TState](FSharpFunc`2 folder, IEnumerable`1 source, TState state)
   at Fable.Tools.ProjectCracker.getProjectOptionsFromFsproj(String projFile)
   at Fable.Tools.ProjectCracker.retry@369(FSharpChecker checker, String[] define, String projFile, DateTime retryUntil, Unit unitVar0)
   at Fable.Tools.ProjectCracker.retryGetProjectOpts(FSharpChecker checker, String[] define, String projFile)
   at Fable.Tools.ProjectCracker.getFullProjectOpts(FSharpChecker checker, String[] define, String projFile)
   at Fable.Tools.State.createProject(FSharpChecker checker, FSharpOption`1 projInfo, ICompiler com, Message msg, String projFile)
   at Fable.Tools.State.updateState(FSharpChecker checker, Compiler com, FSharpMap`2 state, Message msg)
   at Fable.Tools.State.loop@315-3.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@841.Invoke(AsyncParams`1 args)

```
### Workaround

Changing the project to target netstandard1.6 instead will make the fable command work correctly, but then `dotnet test` won't work until I flip back to targeting netcoreapp.

### Related information

* Fable version (`dotnet fable --version`): 1.1.5
* Operating system: Windows

**Comment by johlrich** [comment]
Actually figure out a workaround that allows both tools to work without switching targets: Take advantage of the fact that fable's cracker doesn't seem to recognize commented lines.

```
  <PropertyGroup>
    <!--<TargetFramework>netstandard1.6</TargetFramework>-->
    <TargetFramework>netcoreapp1.0</TargetFramework>
  </PropertyGroup>
```

msbuild will use netcoreapp1.0 and fable will use the commented netstandard1.6

**Comment by alfonsogarciacaro** [comment]
Hehe, nice hack :wink: However, this should probably be fixed. Actually Fable is using a proper XML parser to read the .fsproj, but just for the TargetFramework I took a dirty approach and [used regex directly](https://github.com/fable-compiler/Fable/blob/51ed85132225491a2fe472051db98b08b4301c54/src/dotnet/Fable.Tools/ProjectCracker.fs#L308). I was thinking in the case netcoreapp is targeted, and I'm changing that to netstandard but forgot that 1.0 should also change to 1.6 😅 (moreover, I just noticed [these lines are wrong](https://github.com/fable-compiler/Fable/blob/51ed85132225491a2fe472051db98b08b4301c54/src/dotnet/Fable.Tools/ProjectCracker.fs#L318-L319)). I'll fix it :+1:

BTW, how can you make the `dotnet test` command work with Fable? 🤔

**Comment by johlrich** [comment]
Oh, I should have been more clear about the use case as `dotnet test` isn't actually running Fable.

I ran into this building libraries consumed by both js and .net apps (shared modules between server/client) where the .net target runs with `dotnet test` and js target runs `dotnet fable npm-test`. Both commands are executed by fake. It works quite well.

The only thing that could make that story any better would be using Expecto on both sides instead of the xunit/Fable.Plugins.NUnit combo like this repo.

**Comment by alfonsogarciacaro** [comment]
Ah, ok, thanks for the explanation! At the time I wrote the tests for this repo Expecto didn't exist, but yes, it'll be nice to have a way to run tests for Fable with an API similar to Expecto. I never find the time to write it, but I guess we could just create a layer to provide the Expecto-like API and just invoke another JS test library, like Mocha or Jest.
