### ISSUE TITLE
Current Fable Template has invalid nodes packages

### ISSUE THREAD

**Issue by isaacabraham** [fable-compiler/Fable#1107]
### Description

Downloaded the latest Fable template and created an empty fable project. Having done dotnet restore and npm install, I tried to launch the canvas app. However, the app does not run correctly, with the error:

```
ERROR in (webpack)-dev-server/client/socket.js
Module not found: Error: Can't resolve 'sockjs-client' in 'C:\Users\Isaac\Source\Repos\FableApp\node_modules\webpack-dev-server\client'
 @ (webpack)-dev-server/client/socket.js 1:13-37
 @ (webpack)-dev-server/client?http://localhost:8080
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/FableApp.fsproj
```

### Repro code

1. Download latest Fable template: `dotnet new -i "Fable.Template::*`
2. `dotnet restore`
3. `npm install`
4. `dotnet fable npm-run start`

### Expected and actual results

I expected the Fable app to start up properly: -

```Fable (1.1.17) daemon started on port 61225
CWD: C:\Users\Isaac\Source\Repos\FableApp
cmd /C npm run start

> @ start C:\Users\Isaac\Source\Repos\FableApp
> webpack-dev-server

Bundling for development...
Project is running at http://localhost:8080/
webpack output is served from /
Content not from webpack is served from C:\Users\Isaac\Source\Repos\FableApp\public
Parsing ./FableApp.fsproj...
fable: Compiled src\FableApp.fsproj
fable: Compiled src\App.fs
Hash: 8600ccd63dfb2879ebe4
Version: webpack 2.6.1
Time: 6002ms
        Asset    Size  Chunks                    Chunk Names
    bundle.js  316 kB       0  [emitted]  [big]  main
bundle.js.map  375 kB       0  [emitted]         main
chunk    {0} bundle.js, bundle.js.map (main) 302 kB [entry] [rendered]
   [35] ./src/FableApp.fsproj 25 bytes {0} [built]
   [36] (webpack)-dev-server/client?http://localhost:8080 5.78 kB {0} [built]
   [37] ./~/ansi-html/index.js 4.26 kB {0} [built]
   [38] ./~/ansi-regex/index.js 135 bytes {0} [built]
   [40] ./~/events/events.js 8.33 kB {0} [built]
   [41] ./src/App.fs 332 bytes {0} [built]
   [46] ./~/punycode/punycode.js 14.7 kB {0} [built]
   [52] ./~/sockjs-client/lib/entry.js 244 bytes {0} [built]
   [78] ./~/strip-ansi/index.js 161 bytes {0} [built]
   [79] ./~/url/url.js 23.3 kB {0} [built]
   [80] ./~/url/util.js 314 bytes {0} [built]
   [81] (webpack)-dev-server/client/overlay.js 3.73 kB {0} [built]
   [82] (webpack)-dev-server/client/socket.js 897 bytes {0} [built]
   [84] (webpack)/hot/emitter.js 77 bytes {0} [built]
   [85] multi (webpack)-dev-server/client?http://localhost:8080 ./src/FableApp.fsproj 40 bytes {0} [built]
     + 71 hidden modules
webpack: Compiled successfully.
```

But I saw this instead:

```
Fable (1.1.17) daemon started on port 61225
CWD: C:\Users\Isaac\Source\Repos\FableApp
cmd /C npm run start

> @ start C:\Users\Isaac\Source\Repos\FableApp
> webpack-dev-server

module.js:328
    throw err;
    ^

Error: Cannot find module 'watchpack'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Isaac\Source\Repos\FableApp\node_modules\webpack\lib\node\NodeWatchFileSystem.js:7:19)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
 npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `webpack-dev-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Isaac\AppData\Roaming\npm-cache\_logs\2017-08-09T14_36_14_499Z-debug.log
Closing Fable daemon...
```

### Workaround
I was able to fix it by rolling back some dependencies in `package.json`: webpack and webpack-dev-server.

### Related information

* Fable version (`dotnet fable --version`): 1.1.7
* Operating system: Win10

**Comment by alfonsogarciacaro** [comment]
Weird, I test the templates before publishing. I've published a new version (Fable.Template 1.1.11) and this time I've tested it in advance using both yarn and npm, could you please update it and check if it works? Thanks!

**Comment by MangelMaxime** [comment]
I installed the latest template yesterday and didn't have any problem.

@isaacabraham Is the latest template ok for you ?

**Comment by isaacabraham** [comment]
Sorry Didn't see the earlier message. I'll test tomorrow.

**Comment by alfonsogarciacaro** [comment]
I'll close the issue for now, please feel free to reopen if latest template isn't working.

**Comment by isaacabraham** [comment]
Doh. Sorry that I never got around to re-testing. Happy to re-open when I finally get around to it.
