### ISSUE TITLE
It was not possible to find any compatible framework version

### ISSUE THREAD

**Issue by amsterdamharu** [fable-compiler/Fable#1114]
### Description

I guess this was mentioned [here](https://github.com/fable-compiler/Fable/issues/1042#issuecomment-320495025) but that is probably a separate issue.
 Getting [started](http://fable.io/pages/getting-started.html) does not work on Fedora with the error:

```
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '1.0.4' was not found.
  - Check application dependencies and target a framework version installed at:
      /
  - Alternatively, install the framework version '1.0.4'.

```

Some information

```
[me@localhost src]$ mono --version
Mono JIT compiler version 5.0.1.1 (2017-02/5077205 Wed May 24 13:16:08 UTC 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)

[me@localhost src]$ dotnet --info
.NET Command Line Tools (2.1.0-preview1-007012)

Product Information:
 Version:            2.1.0-preview1-007012
 Commit SHA-1 hash:  b60272d64d

Runtime Environment:
 OS Name:     fedora
 OS Version:  25
 OS Platform: Linux
 RID:         fedora.25-x64
 Base Path:   /usr/share/dotnet-sdk-latest-linux-x64/sdk/2.1.0-preview1-007012/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

[me@localhost src]$ dotnet fable --version
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '1.0.4' was not found.
  - Check application dependencies and target a framework version installed at:
      /
  - Alternatively, install the framework version '1.0.4'.

```
I was working with the npm of Fable and that is working fine but noticed the following message when installing

```
npm WARN deprecated fable-compiler@0.7.51: 
Fable is not distributed through npm anymore, check http://fable.io for more info

```
Trying to create a soft link gets me another error:

```
# as su
ln -s /usr/share/dotnet-sdk-latest-linux-x64/shared/Microsoft.NETCore.App/2.0.0 /usr/share/dotnet-sdk-latest-linux-x64/shared/Microsoft.NETCore.App/1.0.4

[me@localhost src]$ dotnet fable yarn-run start

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Threading, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.Console.get_Out()
   at Fable.CLI.Main.startServer(Int32 port, Int32 timeout, FSharpFunc`2 onMessage, FSharpFunc`2 continuation)
   at Fable.CLI.Main.main(String[] argv)

```

Using the [.net core runtime binaries 1.0.4](https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.0.4-download.md) and put the shared/Microsoft.NETCore.App/1.0.4 directory in /usr/share/dotnet-sdk-latest-linux-x64/shared/Microsoft.NETCore.App/ I get the following error:

```
[me@localhost src]$ dotnet fable start
Error: assembly specified in the dependencies manifest was not found -- package: 'FSharp.Compiler.Service', version: '13.0.0', path: 'lib/netstandard1.6/FSharp.Compiler.Service.dll'

```

**Comment by lvicentesanchez** [comment]
I having the same problem with the official release.

**Comment by alfonsogarciacaro** [comment]
I just published a new Fable.Template version with beta support for netcore2, can you please give it a try?

```
dotnet new -i Fable.Template
dotnet new fable -n MyFableApp
cd MyFableApp
```

And check the README for further instructions :)

**Comment by lvicentesanchez** [comment]
@alfonsogarciacaro seems to be working now :)

**Comment by lvicentesanchez** [comment]
At least for me on Arch Linux with 2.0.0 stable release.

**Comment by alfonsogarciacaro** [comment]
Great, thanks for the confirmation @lvicentesanchez!

**Comment by kerams** [comment]
I'm having the exact same problem on Windows with Fable.Template.Elmish.React.Demo and core 2.0.0.

**Comment by MangelMaxime** [comment]
Elmish templates are not updated for netstandard 2.0 format.

**Comment by MangelMaxime** [comment]
Please open an issue on elmish template repo.

**Comment by kerams** [comment]
There's already https://github.com/fable-elmish/templates/issues/25 by the looks if it :)
