### ISSUE TITLE
int and float operator parsing of "0x" "0o" "0b" prefixes differs in Fable vs. .NET F#

### ISSUE THREAD

**Issue by chadunit** [fable-compiler/Fable#1178]
### Description

1. The .NET F# `int` operator works on strings with "0x", "0o", and "0b" prefixes, but these fail in Fable.
2. The .NET F# `float` operator does not support these prefixes, but in Fable they work.

### Repro code

1.
.NET F# `int` works:
```
Microsoft (R) F# Interactive version 4.1
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> let a = int "0x11";;
val a : int = 17

> let a = int "0o11";;
val a : int = 9

> let a = int "0b11";;
val a : int = 3
```

Fable produces the following error for the above `int` statements:
```
App.fs:34 Uncaught Error: Input string was not in a correct format.
    at parse (App.fs:34)
    at Object.__webpack_exports__.a (App.fs:22)
    at __webpack_require__ (bootstrap 6844bd54a990844f9a09:19)
    at Object.__webpack_exports__.e (events.js:302)
    at __webpack_require__ (bootstrap 6844bd54a990844f9a09:19)
    at Object.<anonymous> (bundle.js:6454)
    at __webpack_require__ (bootstrap 6844bd54a990844f9a09:19)
    at module.exports.ctor.super_ (bootstrap 6844bd54a990844f9a09:62)
    at bootstrap 6844bd54a990844f9a09:62
```

2.
.NET F# `float` fails:
```
> let a = float "0x11";;
System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at <StartupCode$FSI_0005>.$FSI_0005.main@()
Stopped due to error

> let a = float "0o11";;
System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at <StartupCode$FSI_0006>.$FSI_0006.main@()
Stopped due to error

> let a = float "0b11";;
System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at <StartupCode$FSI_0007>.$FSI_0007.main@()
Stopped due to error
```
Fable successfully executes the above `float` statements.

### Related information

* Fable version (`dotnet fable --version`): 1.2.4
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
Thanks for pointing this out, I've improved the regex validation when parsing integers 👍  For floats, though it's not ideal that the behaviour differs from .NET, at the moment we're just defaulting to JS native float parsing so it's difficult to get exactly the same semantics. I hope that's fine.

**Comment by chadunit** [comment]
Great, that's fine by me, ints are the more important issue so as not to break otherwise working code.
