### ISSUE TITLE
locked fs files more often during watch recompilation

### ISSUE THREAD

**Issue by ctaggart** [fable-compiler/Fable#1240]
### Description

When working on `ts2fabel`, I run `dotnet fable yarn-watch` from the `src` directory a lot. Since upgrading to Fable 1.3.0, I appear to run into a .fs file being locked much more often:

```
fable: Compilation started at 11:51:03
Parsing ./ts2fable.fs...
ERROR: The process cannot access the file 'C:\Users\camer\fs\ts2fable\src\ts2fable.fs' because it is being used by another process.
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at Fable.CLI.StateUtil.createProject@75-6.Invoke(String dirtyFile)
   at Microsoft.FSharp.Collections.ArrayModule.Fold[T,TState](FSharpFunc`2 folder, TState state, T[] array)
   at Fable.CLI.StateUtil.createProject(FSharpChecker checker, String[] dirtyFiles, FSharpOption`1 prevProject, Message msg, String projFile)
   at Fable.CLI.StateUtil.checkWatchCompilation@143(FSharpChecker checker, Message msg, FSharpMap`2 state, Project project, String sourceFile)
   at Fable.CLI.StateUtil.tryFindAndUpdateProject@160-1.Invoke(String _arg1, Project project)
   at Fable.CLI.StateUtil.updateState(FSharpChecker checker, FSharpMap`2 state, Message msg)
   at Fable.CLI.StateUtil.loop@223-6.Invoke(Tuple`2 _arg1)
ERROR: The process cannot access the file 'C:\Users\camer\fs\ts2fable\src\ts2fable.fs' because it is being used by another process.
```

I simply stop the watch with a ctrl+c and rerun.

### Related information

* Fable version (`dotnet fable --version`): 1.3.0
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
Hmm, this doesn't happen with Webpack, but the [fable-splitter file watcher is more rudimentary](https://github.com/fable-compiler/Fable/blob/2c7e49f66550a9794e30b6513b7b009d0647f290/src/js/fable-splitter/cli.js#L103). I wonder how can we fix, supposedly [this was introduced to avoid those problems](https://github.com/fable-compiler/Fable/blob/2c7e49f66550a9794e30b6513b7b009d0647f290/src/dotnet/dotnet-fable/ProjectCracker.fs#L281-L298) 😕

**Comment by whitetigle** [comment]
Is this problem related? (got it since 1.3 I think. I'm on 1.3.2 and exact same problem)
 
![image](https://user-images.githubusercontent.com/883207/33218790-0a2961b2-d13f-11e7-9bc8-314579701ecf.png)

**Comment by whitetigle** [comment]
> I simply stop the watch with a ctrl+c and rerun. 

Saving the file again after the error was raised also works

**Comment by alfonsogarciacaro** [comment]
Hmm, I haven't been able to reproduce it yet. I guess it only affects Windows. I tried 1.3.2 on Windows but just very quickly and with a small project. Someone else is seeing this? Any ideas? @MangelMaxime @inosik @forki

**Comment by forki** [comment]
Mhm no idea, but ionide locks files now. @Krzysztof-Cieslak

Am 25.11.2017 12:02 schrieb "Alfonso Garcia-Caro" <notifications@github.com

**Comment by humhei** [comment]
My expreience： 
The vscode will automaticlly lock file while it is saving
So just wait a while to wait it ?
```fsharp
                    let rec read() =
                        try 
                            File.readAsString(change.FullPath)
                        with ex ->
                            Thread.Sleep(100)
                            read()
                    read()
```

**Comment by whitetigle** [comment]
Still happens on my side from time to time. So maybe you found the reason @humhei. Will try that!

**Comment by alfonsogarciacaro** [comment]
What version are you using @humhei? In principle [files shouldn't be locked while reading](https://github.com/fable-compiler/Fable/commit/1ebcef182a8443a33ff11fc7064d2ae5f5911371) now.

**Comment by humhei** [comment]
Maybe have been fixed..... I didn't test it.. (- -)
I just encounted the some issue in my use case (A binding to vscode file and excel cell value)
![image](https://user-images.githubusercontent.com/25994449/49260128-1e36e600-f477-11e8-87f7-8733bf5a89a1.png)
