### ISSUE TITLE
dev2.0 branch - Babel error: "You must pass a scope and parentPath unless traversing a Program/File."

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#1415]
See #700, same thing basically (dev2.0 branch only).

**Comment by ncave** [comment]
Just for reference, a few more errors in the build log: [build log](https://gist.github.com/ncave/941fe05e5d0d1de122cc28e735efc5de)

**Comment by alfonsogarciacaro** [comment]
Thanks @ncave! This error usually happens when we declare two `let` or `const` variables with same name within a block scope in Babel AST. It's unfortunate that Babel doesn't give you the location in the error message, but I guess we can add an extra check to locate the problem.

Hmm, looking at the log it seems this is going to hit hard: `error FABLE: Current version cannot implement ToString for records and unions`. This happens because in Fable 2 methods are static functions except for overrides, which are attached to the prototype. But records and unions are compiled as plain JS objects or arrays so they don't have their own prototype... I need to find a way to solve this.

**Comment by ncave** [comment]
@alfonsogarciacaro Here is an updated build log (with #1418 applied): [build_log](https://gist.github.com/ncave/941fe05e5d0d1de122cc28e735efc5de)

**Comment by ncave** [comment]
@alfonsogarciacaro Thanks for adding the extra logging, it's so much easier to locate the problem now.
Here is a small repro:
```
module App

let test arg =
    match arg with
    | 0 | 1 ->
        let test x = x
        test
    | _ -> id

[<EntryPoint>]
let main argv =
    (test 1) 0
```

causing this Fable error: TypeError: unknown: Duplicate declaration "test$1"
The problem seems to be related to ho many cases are in that match, i.e.:
- match arg with  | 0 | 1 -> fails with above error
- match | 1 -> works

**Comment by alfonsogarciacaro** [comment]
You mean the range in identifiers? That was supposed to be one of the improvements in Fable 2, but I just realized I wasn't copying the location info from the Fable to the Babel AST 😅 Happy to see it has improved the error info for this case!

It seems things that were solved in Fable 1 are hitting me in Fable 2 because I forgot to move the patches in the refactoring. In this case it was about wrapping the `case` statements in a switch with braces to give its own block scope to each. I also took the chance to remove target duplication when possible. Can you please try with latest commit?

**Comment by ncave** [comment]
@alfonsogarciacaro No, I was talking about the commit after tis issue was opened that changed the error to `TypeError: unknown: Duplicate declaration`, which helped a lot.

**Comment by alfonsogarciacaro** [comment]
Then I don't know what I did exactly to change the error message but I'm glad it helped 😅

**Comment by ncave** [comment]
@alfonsogarciacaro The small repro above works now, but there is another error now:
```
ERROR: Found DecisionTree target 0 but length of bindings differ (/FSharp.Compiler.Service_fable/src/fsharp/TypeChecker.fs)
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1645.Invoke(String message)
   at Fable.Transforms.Fable2Babel.Util.transformDecisionTreeSuccessAsStatements(IBabelCompiler com, Context ctx, FSharpOption`1 returnStrategy, Int32 targetIndex, FSharpList`1 boundValues) in \Fable\src\dotnet\Fable.Compiler\Transforms\Fable2Babel.fs:line 909
   at Fable.Transforms.Fable2Babel.Util.transformAsStatements(IBabelCompiler com, Context ctx, FSharpOption`1 returnStrategy,
Expr expr) in \Fable\src\dotnet\Fable.Compiler\Transforms\Fable2Babel.fs:line 1137
   at Fable.Transforms.Fable2Babel.Util.cases@869.Invoke(Tuple`2 tupledArg) in \Fable\src\dotnet\Fable.Compiler\Transforms\Fable2Babel.fs:line 877
   at Microsoft.FSharp.Primitives.Basics.List.collectToFreshConsTail[T,TResult](FSharpFunc`2 f, FSharpList`1 list, FSharpList`1 cons)
   at Microsoft.FSharp.Primitives.Basics.List.collect[T,TResult](FSharpFunc`2 f, FSharpList`1 list)
   at Fable.Transforms.Fable2Babel.Util.transformSwitch(IBabelCompiler com, Context ctx, FSharpOption`1 returnStrategy, Expr evalExpr, FSharpList`1 cases, FSharpOption`1 defaultCase) in \Fable\src\dotnet\Fable.Compiler\Transforms\Fable2Babel.fs:line 868
   at Fable.Transforms.Fable2Babel.Util.transformDecisionTreeAsStaments$cont@958(IBabelCompiler com, Context ctx, FSharpOption`1 returnStrategy, FSharpList`1 targets, Expr treeExpr, Unit unitVar) in \Fable\src\dotnet\Fable.Compiler\Transforms\Fable2Babel.fs:line 984
   at Fable.Transforms.Fable2Babel.Util.transformDecisionTreeAsStaments(IBabelCompiler com, Context ctx, FSharpOption`1 returnStrategy, FSharpList`1 targets, Expr treeExpr) in \Fable\src\dotnet\Fable.Compiler\Transforms\Fable2Babel.fs:line 997
   at Fable.Transforms.Fable2Babel.Util.transformAsStatements(IBabelCompiler com, Context ctx, FSharpOption`1 returnStrategy,
Expr expr) in \Fable\src\dotnet\Fable.Compiler\Transforms\Fable2Babel.fs:line 1089
   at Fable.Transforms.Fable2Babel.Util.transformDecisionTreeSuccessAsStatements(IBabelCompiler com, Context ctx, FSharpOption`1 returnStrategy, Int32 targetIndex, FSharpList`1 boundValues) in \Fable\src\dotnet\Fable.Compiler\Transforms\Fable2Babel.fs:line 918
   at Fable.Transforms.Fable2Babel.Util.transformAsStatements(IBabelCompiler com, Context ctx, FSharpOption`1 returnStrategy,
Expr expr) in \Fable\src\dotnet\Fable.Compiler\Transforms\Fable2Babel.fs:line 1137
   at Fable.Transforms.Fable2Babel.Util.transformIfStatement(IBabelCompiler com, Context ctx, FSharpOption`1 ret, Expression guardExpr, Expr thenStmnt, Expr elseStmnt) in \Fable\src\dotnet\Fable.Compiler\Transforms\Fable2Babel.fs:line 719
   at Fable.Transforms.Fable2Babel.Util.transformIfStatement(IBabelCompiler com, Context ctx, FSharpOption`1 ret, Expression guardExpr, Expr thenStmnt, Expr elseStmnt) in \Fable\src\dotnet\Fable.Compiler\Transforms\Fable2Babel.fs:line 722
   at Fable.Transforms.Fable2Babel.Util.transformAsStatements(IBabelCompiler com, Context ctx, FSharpOption`1 returnStrategy,
Expr expr) in \Fable\src\dotnet\Fable.Compiler\Transforms\Fable2Babel.fs:line 1116
   at Fable.Transforms.Fable2Babel.Util.transformFunction(IBabelCompiler com, Context ctx, FSharpOption`1 name, FSharpList`1 args, Expr body) in \Fable\src\dotnet\Fable.Compiler\Transforms\Fable2Babel.fs:line 1169
   at Fable.Transforms.Fable2Babel.Util.getMemberArgsAndBody(IBabelCompiler com, Context ctx, FSharpOption`1 name, FSharpOption`1 boundThis, FSharpList`1 args, Boolean hasSpread, Expr body) in \Fable\src\dotnet\Fable.Compiler\Transforms\Fable2Babel.fs:line 255
   at Fable.Transforms.Fable2Babel.Util.transformModuleFunction(IBabelCompiler com, Context ctx, ValueDeclarationInfo info, FSharpList`1 args, Expr body) in \Fable\src\dotnet\Fable.Compiler\Transforms\Fable2Babel.fs:line 1223
   at Fable.Transforms.Fable2Babel.Util.transformDeclarations@1325-1.Invoke(Declaration _arg1) in \Fable\src\dotnet\Fable.Compiler\Transforms\Fable2Babel.fs:line 1333
   at Microsoft.FSharp.Primitives.Basics.List.collectToFreshConsTail[T,TResult](FSharpFunc`2 f, FSharpList`1 list, FSharpList`1 cons)
   at Microsoft.FSharp.Primitives.Basics.List.collect[T,TResult](FSharpFunc`2 f, FSharpList`1 list)
   at Fable.Transforms.Fable2Babel.Compiler.transformFile(ICompiler com, File file) in \Fable\src\dotnet\Fable.Compiler\Transforms\Fable2Babel.fs:line 1464
```

**Comment by ncave** [comment]
@alfonsogarciacaro Somehow [this ](https://github.com/fable-compiler/Fable/blob/dev2.0/src/dotnet/Fable.Compiler/Transforms/Fable2Babel.fs#L99)was not triggering before, but now it does, is it related to the fix that you did above?
> wrapping the `case` statements in a switch with braces to give its own block scope

**Comment by alfonsogarciacaro** [comment]
Hmm, could be. It may be also that somehow I'm not [putting the decision targets in the context](https://github.com/fable-compiler/Fable/blob/bfd926eec5e72748cc977d6b5130df47096b6f3e/src/dotnet/Fable.Compiler/Transforms/Fable2Babel.fs#L987) in the right places and the compiler is finding the target of a parent tree in nested pattern matching. I'll check.

**Comment by ncave** [comment]
@alfonsogarciacaro Here is a small repro:
```
module App

let test x = 
    match x with 
    | (4 | 5) as r -> r
    | _ -> 1

[<EntryPoint>]
let main argv =
    test 2
```
ERROR: Cannot find DecisionTree target 0

**Comment by ncave** [comment]
@alfonsogarciacaro And a slightly bigger repro:
```
module App

let test x =
    match x with 
    | 1 -> 1
    | 2 ->
        match x with 
        | (4 | 5) as r -> r
        | _ -> 1
    | _ -> 0

[<EntryPoint>]
let main argv =
    test 2
```
ERROR: Found DecisionTree target 0 but length of bindings differ

**Comment by ncave** [comment]
@alfonsogarciacaro Seems to work now, thanks for fixing it.

**Comment by alfonsogarciacaro** [comment]
Thanks to you! As expected the fix was easy, but thanks to the tests we can be sure no regressions will happen :clap:
