### ISSUE TITLE
(2.0.0-beta-005) Cannot find inline member

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#1575]
When compiling FCS with Fable 2.0.0-beta-005, the following error occurs:
```
ERROR: Cannot find inline member Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.StartsWithOrdinal (/Projects/FSharp.Compiler.Service_fable/src/fsharp/ast.fs)
   at Fable.Transforms.FSharp2Fable.Compiler.Fable-Transforms-FSharp2Fable-IFableCompiler-GetInlineExpr@949.Invoke(Unit unitVar0)   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Fable.Transforms.FSharp2Fable.Util.inlineExpr[a](IFableCompiler com, Context ctx, FSharpOption`1 r, Lazy`1 genArgs, FSharpOption`1 callee, FSharpList`1 args, FSharpMemberOrFunctionOrValue memb)
   at Fable.Transforms.FSharp2Fable.Util.makeCallFrom(IFableCompiler com, Context ctx, FSharpOption`1 r, Type typ, Boolean isBaseCall, IEnumerable`1 genArgs, FSharpOption`1 callee, FSharpList`1 args, FSharpMemberOrFunctionOrValue memb)
   at Fable.Transforms.FSharp2Fable.Compiler.transformExpr@355-32.Invoke(FSharpList`1 _arg26)
   at MonadicTrampoline.MonadicTrampoline-IBind-1-Bind@32.Invoke(T t)
   at MonadicTrampoline.Bind`2.MonadicTrampoline-ITrampoline`1-Run()
   at Fable.Transforms.FSharp2Fable.Compiler.transformMemberFunction(IFableCompiler com, Context ctx, Boolean isPublic, String name, FSharpMemberOrFunctionOrValue memb, FSharpList`1 args, FSharpExpr body)
   at Fable.Transforms.FSharp2Fable.Compiler.transformMemberFunctionOrValue(IFableCompiler com, Context ctx, FSharpMemberOrFunctionOrValue memb, FSharpList`1 args, FSharpExpr body)
   at Fable.Transforms.FSharp2Fable.Compiler.transformDeclarationsInner@838-1.Invoke(FSharpImplementationFileDeclaration fsDecl)
   at Microsoft.FSharp.Primitives.Basics.List.collectToFreshConsTail[T,TResult](FSharpFunc`2 f, FSharpList`1 list, FSharpList`1 cons)
   at Microsoft.FSharp.Primitives.Basics.List.collect[T,TResult](FSharpFunc`2 f, FSharpList`1 list)
   at Fable.Transforms.FSharp2Fable.Compiler.transformFile(ICompiler com, FSharpMap`2 implFiles)
ERROR: Cannot find inline member Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.StartsWithOrdinal (/Projects/FSharp.Compiler.Service_fable/src/fsharp/ast.fs)
Closing Fable daemon...
```
Strange enough, it's not happening when the REPL is being compiled (which also compiles the same project). It could be some path issue, from the error description, possibly related to [this commit](https://github.com/fable-compiler/Fable/commit/989a25c0c0db578c189a1be135d74e5f1bd3a58c#diff-792c96facecb15a073e092535ba4c830).

**Comment by alfonsogarciacaro** [comment]
Actually something similar happened to me in another project, not sure if it's related to the FCS upgrade. In my case, I think cleaning the repo with `git clean -xfd` and recompiling just worked :/

**Comment by ncave** [comment]
@alfonsogarciacaro Unfortunately that does not help. It only works within Fable, but outside, when using dotnet-fable 2.0.0-beta-005, it triggers the error above. Somehow it can't find the inline member in the dictionary, but I can't debug it cause it's only happening with the packaged dotnet-fable tool.

Easy to reproduce though, by building the [FCS-Fable test project](https://github.com/ncave/FSharp.Compiler.Service/tree/fable/fcs/fcs-fable/test):

`fcs\build codegen.fable & cd fcs/fcs-fable/test & npm install & npm build`

**Comment by alfonsogarciacaro** [comment]
The commit linked in the first commit is older than the 005 release, so the problem may be a couple of versions older 🤔 Also, the link above is for the `fable` branch of your fork, that may explain why the REPL builds fine (it uses `fable2` branch).

**Comment by alfonsogarciacaro** [comment]
Scratch that, I think I found it. Can you please try again with latest master? Thanks a lot for the detailed report!

**Comment by ncave** [comment]
@alfonsogarciacaro That worked, thanks for fixing it.

**Comment by alfonsogarciacaro** [comment]
Great, thanks for confirming!
