### ISSUE TITLE
Fable 2.0 compiler error "You must pass a scope and parentPath unless traversing..." when using same member name in module

### ISSUE THREAD

**Issue by SirUppyPancakes** [fable-compiler/Fable#1607]
### Description

When having two members with the same name (in this case a type and function), where the type is private, Fable produces a cryptic compilation error.

### Repro code

1. Download the attached example:  [fable2_same_member_name.zip](https://github.com/fable-compiler/Fable/files/2480783/fable2_same_member_name.zip)
2. Run `yarn install`
3. Run `yarn start`
4. Observe the compilation error

Excerpt:

`Test.fs`
```
module Test

type private A() = class end

let A() = printfn "test"
```
`App.fs`
```
module fable2_same_member_name

open Test

A()
```

### Expected and actual results

This should compile fine, but instead produces the following compiler error:
```
ERROR in ./src/Test.fs
Module build failed (from ./node_modules/fable-loader/index.js):
Error: You must pass a scope and parentPath unless traversing a Program/File. Instead of that you tried to traverse a Identifier node without passing scope and parentPath.
    at traverse (C:\Users\caleb\Downloads\fable2_same_member_name\fable2_same_member_name\node_modules\@babel\traverse\lib\index.js:71:13)
    at File.buildCodeFrameError (C:\Users\caleb\Downloads\fable2_same_member_name\fable2_same_member_name\node_modules\@babel\core\lib\transformation\file\file.js:240:31)
    at Scope.checkBlockScopedCollisions (C:\Users\caleb\Downloads\fable2_same_member_name\fable2_same_member_name\node_modules\@babel\traverse\lib\scope\index.js:347:22)
    at Scope.registerBinding (C:\Users\caleb\Downloads\fable2_same_member_name\fable2_same_member_name\node_modules\@babel\traverse\lib\scope\index.js:504:16)
    at Scope.registerDeclaration (C:\Users\caleb\Downloads\fable2_same_member_name\fable2_same_member_name\node_modules\@babel\traverse\lib\scope\index.js:439:12)
    at Object.BlockScoped (C:\Users\caleb\Downloads\fable2_same_member_name\fable2_same_member_name\node_modules\@babel\traverse\lib\scope\index.js:189:28)
    at Object.newFn (C:\Users\caleb\Downloads\fable2_same_member_name\fable2_same_member_name\node_modules\@babel\traverse\lib\visitors.js:230:17)
    at NodePath._call (C:\Users\caleb\Downloads\fable2_same_member_name\fable2_same_member_name\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (C:\Users\caleb\Downloads\fable2_same_member_name\fable2_same_member_name\node_modules\@babel\traverse\lib\path\context.js:36:14)
    at NodePath.visit (C:\Users\caleb\Downloads\fable2_same_member_name\fable2_same_member_name\node_modules\@babel\traverse\lib\path\context.js:88:12)
 @ ./src/App.fs 1:0-105 2:0-1
 @ ./src/fable2_test.fsproj
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./src/fable2_test.fsproj
```

The workaround for this is to simply not name things the same ;)

### Related information

* Fable version (`dotnet fable --version`): 2.0.3
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
Ah, yes, this is Babel error when there are two `let/const` values with the same name in the same scope, it took me a long time to find it out. Interesting, I didn't know this was possible in F#. I guess it's not very necessary to support it in Fable but you're right in that we should provide a better error message. I'll add a check to find types and module members with same name :+1:
