### ISSUE TITLE
Error NU1100: Unable to resolve 'dotnet-fable (>= 1.3.7)' for '.NETCoreApp,Version=v2.1'

### ISSUE THREAD

**Issue by vasily-kirichenko** [fable-compiler/Fable#1643]
```
...\src\Client\Client.fsproj : error NU1100: Unable to resolve 'dotnet-fable (>= 1.3.7)' for '.NETCoreApp,Version=v2.1'.
C:\Program Files\dotnet\sdk\2.1.403\NuGet.targets(114,5): error : Value cannot be null. [C:\WLCR\stash\KlSrl.Insight\src\Client\KlSrl.Insight.Client.fsproj]
C:\Program Files\dotnet\sdk\2.1.403\NuGet.targets(114,5): error : Parameter name: path [C:\WLCR\stash\KlSrl.Insight\src\Client\KlSrl.Insight.Client.fsproj]
Running build failed.
Error:
System.Exception: dotnet restore failed
   at FSI_0005.Build.runDotnet@56.Invoke(String message)
   at FSI_0005.Build.runDotnet(String workingDir, String args)
   at FSI_0005.Build.clo@184-11.Invoke(Unit _arg2)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\fake\src\app\FakeLib\TargetHelper.fs:line 626
```

**Comment by vasily-kirichenko** [comment]
Thanks. I'm using a very old Fable (~9 months old). Started to upgrade to the latest, so I'm closing this issue.
