### ISSUE TITLE
Fable-loader 2.1: compilation fails

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/Fable#1657]
Hi,
just tried to upgrade my project to fable-loader lastest. But it seems that I failed to do something because my build fails with error: 

```
Bundling for prod...
fable-compiler 2.1.2
D:\workspace\server\src> dotnet restore Server.fsproj
  Paket version 5.193.0
  The last restore is still up to date. Nothing left to do.
  Performance:
   - Runtime: 110 milliseconds
  Restauration effectu�e dans 36,27 ms pour D:\workspace\server\src\Server.fsproj.


ERROR: MSBuild failed with exitCode 1 Working Directory: 'D:\workspace\server\src' Exe Path: 'dotnet' Args: 'msbuild D:\workspace\server\src\Server.fsproj /p:SkipCompilerExecution=true /p:ProvideCommandLineArgs=true /p:CopyBuildOutputToOutputDirectory=false /p:UseCommonOutputDirectory=true /t:_Inspect_FscArgs /p:_Inspect_FscArgs_OutFile=C:\Users\whitetigle\AppData\Local\Temp\tmp5674.tmp.FscArgs.txt /p:DesignTimeBuild=true /t:_Inspect_GetResolvedProjectReferences /p:_Inspect_GetResolvedProjectReferences_OutFile=C:\Users\whitetigle\AppData\Local\Temp\tmp5675.tmp.GetResolvedProjectReferences.txt /t:_Inspect_GetProperties /p:_Inspect_GetProperties_OutFile=C:\Users\whitetigle\AppData\Local\Temp\tmp5695.tmp.GetProperties.txt /p:CustomAfterMicrosoftCommonTargets=C:\Users\whitetigle\AppData\Local\Temp\tmp56A6.tmp.proj-info.hook.targets /nologo /verbosity:quiet'
   at Fable.CLI.ProjectCoreCracker.projInfo(FSharpList`1 additionalMSBuildProps, String file) in /Users/alfonsogarciacaronunez/dev/fable/src/dotnet/Fable.Compiler/CLI/ProjectCoreCracker.fs:line 103
   at Fable.CLI.ProjectCracker.fullCrack(String projFile) in /Users/alfonsogarciacaronunez/dev/fable/src/dotnet/Fable.Compiler/CLI/ProjectCracker.fs:line 202
   at Fable.CLI.ProjectCracker.getCrackedProjectsFromMainFsproj(String projFile) in /Users/alfonsogarciacaronunez/dev/fable/src/dotnet/Fable.Compiler/CLI/ProjectCracker.fs:line 277
   at Fable.CLI.ProjectCracker.retry@298(FSharpChecker checker, String projFile, DateTime retryUntil, Unit unitVar0) in /Users/alfonsogarciacaronunez/dev/fable/src/dotnet/Fable.Compiler/CLI/ProjectCracker.fs:line 300
   at Fable.CLI.ProjectCracker.getFullProjectOpts(FSharpChecker checker, String[] define, String rootDir, String projFile) in /Users/alfonsogarciacaronunez/dev/fable/src/dotnet/Fable.Compiler/CLI/ProjectCracker.fs:line 362
   at Fable.CLI.Agent.createProject(FSharpChecker checker, String[] dirtyFiles, FSharpOption`1 prevProject, Message msg, String projFile) in /Users/alfonsogarciacaronunez/dev/fable/src/dotnet/Fable.Compiler/CLI/Agent.fs:line 57
   at Fable.CLI.Agent.updateState(FSharpChecker checker, FSharpMap`2 state, Message msg) in /Users/alfonsogarciacaronunez/dev/fable/src/dotnet/Fable.Compiler/CLI/Agent.fs:line 190
   at Fable.CLI.Agent.loop@260-7.Invoke(Unit unitVar) in /Users/alfonsogarciacaronunez/dev/fable/src/dotnet/Fable.Compiler/CLI/Agent.fs:line 262
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2)
   at <StartupCode$FSharp-Core>.$Mailbox.processFirstArrival@344-8.Invoke(AsyncActivation`1 ctxt)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
Hash: a1f4c280df3d00380d6d
Version: webpack 4.26.1
Time: 5808ms
Built at: 2018-12-03 13:34:23
 1 asset
Entrypoint main = server.js
[0] ./src/Server.fsproj 1.21 KiB {0} [built] [failed] [1 error]

```

here is my webpack.conf.js: 
```js
var nodeExternals = require('webpack-node-externals');
var path = require("path");

var babelOptions = {
  presets: [
    ["@babel/preset-env", {
      "targets": {
        "node": true,
        "uglify": true
      },
      "modules": false
    }]
  ],
};

console.log("Bundling for prod...");

module.exports = {
  mode: "production",
  target: "node",
  node: {
    __dirname: false,
    __filename: false,
  },
  externals: [nodeExternals()],
  entry: './src/Server.fsproj',
  output: {
    path: path.join(__dirname, "./dist"),
    filename: 'server.js',
  },
  plugins: [],
  module: {
    rules: [{
        test: /\.fs(x|proj)?$/,
        use: {
          loader: "fable-loader",
          options: {
            babel: babelOptions,
            define: [] 
          }
        }
      },
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: babelOptions
        },
      }
    ]
  },
};
```

Command I ran: `npx webpack -p --config tools/webpack.config.prod.js`

Thanks for your help!

**Comment by whitetigle** [comment]
with verbose flag: 

```
npx webpack -p --config tools/webpack.config.prod.js  --verbose
Bundling for prod...
fable-compiler 2.1.2
D:\workspace\server\src> dotnet restore Server.fsproj
  Paket version 5.193.0
  The last restore is still up to date. Nothing left to do.
  Performance:
   - Runtime: 90 milliseconds
  Restauration effectu�e dans 34,96 ms pour D:\workspace\server\src\Server.fsproj.


ERROR: MSBuild failed with exitCode 1 Working Directory: 'D:\workspace\server\src' Exe Path: 'dotnet' Args: 'msbuild D:\workspace\server\src\Server.fsproj /p:SkipCompilerExecution=true /p:ProvideCommandLineArgs=true /p:CopyBuildOutputToOutputDirectory=false /p:UseCommonOutputDirectory=true /t:_Inspect_FscArgs /p:_Inspect_FscArgs_OutFile=C:\Users\whitetigle\AppData\Local\Temp\tmp4F2E.tmp.FscArgs.txt /p:DesignTimeBuild=true /t:_Inspect_GetResolvedProjectReferences /p:_Inspect_GetResolvedProjectReferences_OutFile=C:\Users\whitetigle\AppData\Local\Temp\tmp4F2F.tmp.GetResolvedProjectReferences.txt /t:_Inspect_GetProperties /p:_Inspect_GetProperties_OutFile=C:\Users\whitetigle\AppData\Local\Temp\tmp4F40.tmp.GetProperties.txt /p:CustomAfterMicrosoftCommonTargets=C:\Users\whitetigle\AppData\Local\Temp\tmp4F41.tmp.proj-info.hook.targets /nologo /verbosity:quiet'
   at Fable.CLI.ProjectCoreCracker.projInfo(FSharpList`1 additionalMSBuildProps, String file) in /Users/alfonsogarciacaronunez/dev/fable/src/dotnet/Fable.Compiler/CLI/ProjectCoreCracker.fs:line 103
   at Fable.CLI.ProjectCracker.fullCrack(String projFile) in /Users/alfonsogarciacaronunez/dev/fable/src/dotnet/Fable.Compiler/CLI/ProjectCracker.fs:line 202
   at Fable.CLI.ProjectCracker.getCrackedProjectsFromMainFsproj(String projFile) in /Users/alfonsogarciacaronunez/dev/fable/src/dotnet/Fable.Compiler/CLI/ProjectCracker.fs:line 277
   at Fable.CLI.ProjectCracker.retry@298(FSharpChecker checker, String projFile, DateTime retryUntil, Unit unitVar0) in /Users/alfonsogarciacaronunez/dev/fable/src/dotnet/Fable.Compiler/CLI/ProjectCracker.fs:line 300
   at Fable.CLI.ProjectCracker.getFullProjectOpts(FSharpChecker checker, String[] define, String rootDir, String projFile) in /Users/alfonsogarciacaronunez/dev/fable/src/dotnet/Fable.Compiler/CLI/ProjectCracker.fs:line 362
   at Fable.CLI.Agent.createProject(FSharpChecker checker, String[] dirtyFiles, FSharpOption`1 prevProject, Message msg, String projFile) in /Users/alfonsogarciacaronunez/dev/fable/src/dotnet/Fable.Compiler/CLI/Agent.fs:line 57
   at Fable.CLI.Agent.updateState(FSharpChecker checker, FSharpMap`2 state, Message msg) in /Users/alfonsogarciacaronunez/dev/fable/src/dotnet/Fable.Compiler/CLI/Agent.fs:line 190
   at Fable.CLI.Agent.loop@260-7.Invoke(Unit unitVar) in /Users/alfonsogarciacaronunez/dev/fable/src/dotnet/Fable.Compiler/CLI/Agent.fs:line 262
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2)
   at <StartupCode$FSharp-Core>.$Mailbox.processFirstArrival@344-8.Invoke(AsyncActivation`1 ctxt)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
Hash: 650f49601d795448ed49
Version: webpack 4.26.1
Time: 3201ms
Built at: 2018-12-03 13:52:55
 1 asset
Entrypoint main = server.js
chunk    {0} server.js (main) 1.21 KiB [entry] [rendered]
    > ./src/Server.fsproj main
 [0] ./src/Server.fsproj 1.21 KiB {0} [depth 0] [built] [failed] [1 error]
     ModuleConcatenation bailout: Module is not an ECMAScript module
     single entry ./src/Server.fsproj  main

ERROR in ./src/Server.fsproj
Module build failed (from ./node_modules/fable-loader/index.js):
Error: MSBuild failed with exitCode 1 Working Directory: 'D:\workspace\server\src' Exe Path: 'dotnet' Args: 'msbuild D:\workspace\server\src\Server.fsproj /p:SkipCompilerExecution=true /p:ProvideCommandLineArgs=true /p:CopyBuildOutputToOutputDirectory=false /p:UseCommonOutputDirectory=true /t:_Inspect_FscArgs /p:_Inspect_FscArgs_OutFile=C:\Users\whitetigle\AppData\Local\Temp\tmp4F2E.tmp.FscArgs.txt /p:DesignTimeBuild=true /t:_Inspect_GetResolvedProjectReferences /p:_Inspect_GetResolvedProjectReferences_OutFile=C:\Users\whitetigle\AppData\Local\Temp\tmp4F2F.tmp.GetResolvedProjectReferences.txt /t:_Inspect_GetProperties /p:_Inspect_GetProperties_OutFile=C:\Users\whitetigle\AppData\Local\Temp\tmp4F40.tmp.GetProperties.txt /p:CustomAfterMicrosoftCommonTargets=C:\Users\whitetigle\AppData\Local\Temp\tmp4F41.tmp.proj-info.hook.targets /nologo /verbosity:quiet'
    at Loader.getCompiler.send.then.data (D:\workspace\server\node_modules\fable-loader\index.js:77:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Zaid-Ajaj** [comment]
@whitetigle Can you try building the project with just `dotnet`? i.e. `dotnet build` in your source directory because it looks like that MSBuild is what is failing 

Also looks like MSBuild is using cache files from `C:\Users\whitetigle\AppData\Local\Temp` can you try clear the cache (along with `obj`/`bin`) and rebuild as well?

**Comment by whitetigle** [comment]
ok I will try this. Thanks @Zaid-Ajaj!

**Comment by whitetigle** [comment]
hmm. That's interesting: 

```
C:\Program Files\dotnet\sdk\2.1.402\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(96,5): 
error NETSDK1013: The TargetFramework value 'netstandard2.0' was not recognized. 
```

That's my .fsproj:
```

<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>
			netstandard2.0
		</TargetFramework>
	</PropertyGroup>
	<ItemGroup>
		<Compile Include="somefile.fs" />
	</ItemGroup>
	<Import Project="..\.paket\Paket.Restore.targets" />
</Project>
```

Does it mean I need to get rid of `TargetFramework`? (I'm sorry, I'm not a .Net user and I always stumble on this kind of error)

**Comment by MangelMaxime** [comment]
No but everything is working as expected 🤦‍♂️
