### ISSUE TITLE
Cannot find inline type extensions

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#1667]
Compiling these two files:
```
module M1
open System

type String with
    member inline x.StartsWithOrdinal(value) =
        x.StartsWith(value, StringComparison.Ordinal)
```
and
```
module M2
open M1

let startsWith (x: string) (y: string) = x.StartsWithOrdinal(y)
```
generates the following error:
```
ERROR: Cannot find inline member M1.StartsWithOrdinal (/fable-test/src/test.fs)
   at Fable.Transforms.FSharp2Fable.Compiler.Fable-Transforms-FSharp2Fable-IFableCompiler-GetInlineExpr@1004.Invoke(Unit unitVar0) in \Fable\src\dotnet\Fable.Compiler\Transforms\FSharp2Fable.fs:line 1010
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Fable.Transforms.FSharp2Fable.Util.inlineExpr[a](IFableCompiler com, Context ctx, FSharpOption`1 r, Lazy`1 genArgs, FSharpOption`1 callee, FSharpList`1 args, FSharpMemberOrFunctionOrValue memb) in \Fable\src\dotnet\Fable.Compiler\Transforms\FSharp2Fable.Util.fs:line 960
   at Fable.Transforms.FSharp2Fable.Util.makeCallFrom(IFableCompiler com, Context ctx, FSharpOption`1 r, Type typ, Boolean isBaseCall, IEnumerable`1 genArgs, FSharpOption`1 callee, FSharpList`1 args, FSharpMemberOrFunctionOrValue memb) in \Fable\src\dotnet\Fable.Compiler\Transforms\FSharp2Fable.Util.fs:line 1035
   at Fable.Transforms.FSharp2Fable.Compiler.transformExpr@414-45.Invoke(FSharpList`1 _arg29) in \Fable\src\dotnet\Fable.Compiler\Transforms\FSharp2Fable.fs:line 416
   at MonadicTrampoline.Bind`2.MonadicTrampoline-ITrampoline`1-Run() in \Fable\src\dotnet\Fable.Compiler\Transforms\MonadicTrampoline.fs:line 38
   at Fable.Transforms.FSharp2Fable.Compiler.transformMemberFunction(IFableCompiler com, Context ctx, Boolean isPublic, String name, FSharpMemberOrFunctionOrValue memb, FSharpList`1 args, FSharpExpr body) in \Fable\src\dotnet\Fable.Compiler\Transforms\FSharp2Fable.fs:line 801
   at Fable.Transforms.FSharp2Fable.Compiler.transformMemberFunctionOrValue(IFableCompiler com, Context ctx, FSharpMemberOrFunctionOrValue memb, FSharpList`1 args, FSharpExpr body) in \Fable\src\dotnet\Fable.Compiler\Transforms\FSharp2Fable.fs:line 831
   at Fable.Transforms.FSharp2Fable.Compiler.transformDeclarationsInner@908-1.Invoke(FSharpImplementationFileDeclaration fsDecl) in \Fable\src\dotnet\Fable.Compiler\Transforms\FSharp2Fable.fs:line 941
   at Fable.Transforms.FSharp2Fable.Compiler.transformFile(ICompiler com, FSharpMap`2 implFiles) in \Fable\src\dotnet\Fable.Compiler\Transforms\FSharp2Fable.fs:line 1041
ERROR: Cannot find inline member M1.StartsWithOrdinal (/fable-test/src/test.fs)
```
Strange enough, it works fine sometimes if the project containing these files is referenced by another project, and the other one is compiled. Perhaps something about the inlining is different in that case.

**Comment by ncave** [comment]
No, not precompiled, if I have project A reference project B (by project reference) and that project B has the files listed above, and then we compile project B with Fable. In some cases there will be no error, possibly because the inlining already happened.
