### ISSUE TITLE
Failure to compile with Fable 2 (ProjectCracker.tryGetFablePackage throws)

### ISSUE THREAD

**Issue by danyx23** [fable-compiler/Fable#1724]
### Description

After upgrading a SAFE stack app to Fable 2, the project fails to compile. Concretely, the ProjectCracker.tryGetFablePackage function throws an exception (see stacktrace below). Several ways to upgrade were explored, including copying just the source files over to a newly generated scaffold.

### Repro code

This is unfortunately proprietary code and I suspect that the problem has to do with using custom nuget packages (that include the f# source code as per the fable instructions and that used to work in the old setup). Please let me know if there is anything else I could provide to help diagnose this problem.

One think I noticed that might be related is that the .fable directory does not contain directories for the nuget packages we use even though they are mentioned in the .paket.resolved file in the obj directory. I don't know if this is expected or not?

### Expected and actual results

Fable should compile but it doesn't.

### Related information

* Fable version: yarn info fable-compiler version gives 2.1.11, though below in the logs it says fable-compiler 2.1.8?

* Operating system: Windows (but the problem occurs as well in a docker container build on linux)

Stacktrace:
```
$ C:\projects\code\douglasconnect\edelweiss\csvtoapi2\node_modules\.bin\webpack-cli -p
Bundling for production...
fable-compiler 2.1.8
C:\projects\code\douglasconnect\edelweiss\csvtoapi2\src\Client> dotnet restore Client.fsproj
  Paket version 5.196.2
  The last restore is still up to date. Nothing left to do.
  Performance:
   - Runtime: 187 milliseconds
  Wiederherstellung in "62,36 ms" für "C:\projects\code\douglasconnect\edelweiss\csvtoapi2\src\Client\Client.fsproj" abgeschlossen.


ERROR: In der Auflistung wurde kein Index gefunden, der das Prädikat erfüllt.
   at Microsoft.FSharp.Collections.SeqModule.Find[T](FSharpFunc`2 predicate, IEnumerable`1 source)
   at Fable.CLI.ProjectCracker.tryGetFablePackage(String dllPath) in /Users/alfonsogarciacaronunez/dev/fable/src/dotnet/Fable.Compiler/CLI/ProjectCracker.fs:line 142
   at Fable.CLI.ProjectCracker.fablePkgs@237.Invoke(Tuple`2 tupledArg) in /Users/alfonsogarciacaronunez/dev/fable/src/dotnet/Fable.Compiler/CLI/ProjectCracker.fs:line 238
   at Microsoft.FSharp.Collections.Internal.IEnumerator.choose@165.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Fable.CLI.ProjectCracker.fullCrack(String projFile) in /Users/alfonsogarciacaronunez/dev/fable/src/dotnet/Fable.Compiler/CLI/ProjectCracker.fs:line 237
   at Fable.CLI.ProjectCracker.getCrackedProjectsFromMainFsproj(String projFile) in /Users/alfonsogarciacaronunez/dev/fable/src/dotnet/Fable.Compiler/CLI/ProjectCracker.fs:line 277
   at Fable.CLI.ProjectCracker.retry@298(FSharpChecker checker, String projFile, DateTime retryUntil, Unit unitVar0) in /Users/alfonsogarciacaronunez/dev/fable/src/dotnet/Fable.Compiler/CLI/ProjectCracker.fs:line 300
   at Fable.CLI.ProjectCracker.getFullProjectOpts(FSharpChecker checker, String[] define, String rootDir, String projFile) in /Users/alfonsogarciacaronunez/dev/fable/src/dotnet/Fable.Compiler/CLI/ProjectCracker.fs:line 362
   at Fable.CLI.Agent.createProject(FSharpChecker checker, String[] dirtyFiles, FSharpOption`1 prevProject, Message msg, String projFile) in /Users/alfonsogarciacaronunez/dev/fable/src/dotnet/Fable.Compiler/CLI/Agent.fs:line 57
   at Fable.CLI.Agent.updateState(FSharpChecker checker, FSharpMap`2 state, Message msg) in /Users/alfonsogarciacaronunez/dev/fable/src/dotnet/Fable.Compiler/CLI/Agent.fs:line 190
   at Fable.CLI.Agent.loop@259-7.Invoke(Unit unitVar) in /Users/alfonsogarciacaronunez/dev/fable/src/dotnet/Fable.Compiler/CLI/Agent.fs:line 261
rpFunc`2 part2)
   at <StartupCode$FSharp-Core>.$Mailbox.processFirstArrival@344-8.Invoke(AsyncActivation`1 ctxt)
Hash: 63b3d50ba1d678032420
```

**Comment by inosik** [comment]
Must be one of these two lines:

https://github.com/fable-compiler/Fable/blob/aaa8376f3fe9b835f2572be749041aa12672269f/src/dotnet/Fable.Compiler/CLI/ProjectCracker.fs#L147-L149

> custom nuget packages

How did you create them? By using `paket pack` or `dotnet pack`? Paket doesn't generate framework specific dependency groups by default.

**Comment by danyx23** [comment]
This was done using paket pack. Thanks for the pointer, I'll investigate more!

**Comment by danyx23** [comment]
I tried a couple of things now but I wasn't able to get paket to generate dependency groups. Do you have a pointer of how to get paket to generate these framework specific dependency groups?

**Comment by inosik** [comment]
Take a look at the ["Dependencies" section in the docs on `paket.template`](https://fsprojects.github.io/Paket/template-files.html#Dependencies).
