### ISSUE TITLE
Fable running in Linux with .NET Core 3.1

### ISSUE THREAD

**Issue by ktodyruik** [fable-compiler/Fable#1969]
Hi, I'm trying to get fable running on Linux. Windows setup was pretty straightforward. When I run fable2-samples/minimal, I get the following error:

```
~/Projects/fable2-samples/minimal$ npm start

> @ start /home/kerry/Projects/fable2-samples/minimal
> webpack-dev-server

ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from ./public
fable-compiler 2.3.19
events.js:282
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at Socket._writeGeneric (net.js:779:11)
    at Socket._write (net.js:791:8)
    at doWrite (_stream_writable.js:464:12)
    at writeOrBuffer (_stream_writable.js:446:5)
    at Socket.Writable.write (_stream_writable.js:326:11)
    at /home/kerry/Projects/fable2-samples/minimal/node_modules/fable-compiler/dist/index.js:92:29
    at new Promise (<anonymous>)
    at Object.send (/home/kerry/Projects/fable2-samples/minimal/node_modules/fable-compiler/dist/index.js:89:20)
Emitted 'error' event on Socket instance at:
    at errorOrDestroy (internal/streams/destroy.js:128:12)
    at onwriteError (_stream_writable.js:473:3)
    at processTicksAndRejections (internal/process/task_queues.js:86:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `webpack-dev-server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

My dotnet setup:

```
~/Projects/fable2-samples/minimal$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  19.10
 OS Platform: Linux
 RID:         ubuntu.19.10-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.100/

Host (useful for support):
  Version: 3.1.0
  Commit:  157910edee

.NET Core SDKs installed:
  3.1.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
kerry@kerry-VirtualBox:~/Projects/fable2-samples/minimal$ 
```

**Comment by Zaid-Ajaj** [comment]
Can you try updating Fable to latest? i.e. `npm upgrade fable-compiler`

**Comment by ktodyruik** [comment]
Works! Thanks!

**Comment by MangelMaxime** [comment]
Closing as the issue has been solved
