### ISSUE TITLE
How to debug random build failures or increase verbosity?

### ISSUE THREAD

**Issue by matthid** [fable-compiler/Fable#2005]
### Description

Similar to https://github.com/fable-compiler/Fable/issues/1799
We experience random build failures. In particular:

```
2020-03-31T14:20:19.5195255Z   undefined:1
2020-03-31T14:20:19.5209615Z   {"sourceType":"module","body":[{"specifiers":[{"imported":{"name":"toFail","type":"Identifier"},"local":{"name":"toFail","type":"Identifier"},"type":"ImportSpecifier"},{"imported":{"name":"toText","type":"Identifier"},"local":{"name":"toText","type":"Identifier"},"type":"ImportSpecifier"},{"imported":{"name":"printf","type":"Identifier"},"local":{"name":"printf","type":"Identifier"},"type":"ImportSpecifier"},{"imported":{"name":"validateGuid","type":"Identifier"},"local":{"name":"validateGuid","type":"Identifier"},"type":"ImportSpecifier"},{"imported":{"name":"join","type":"Identifier"},"local":{"name":"join","type":"Identifier"},"type":"ImportSpecifier"}],"source":{"value":"../fable-library.2.4.22/String.js","type":"StringLiteral"},"type":"ImportDeclaration"},{"specifiers":[{"imported":{"name":"int16ToString","type":"Identifier"},"local":{"name":"int16ToString","type":"Identifier"},"type":"ImportSpecifier"},{"imported":{"name":"mapCurriedArgs","type":"Identifier"},"local":{"name":"mapCurriedArg
2020-03-31T14:20:19.5210365Z   
2020-03-31T14:20:19.5210631Z   SyntaxError: Unexpected end of JSON input
2020-03-31T14:20:19.5212066Z       at JSON.parse (<anonymous>)
2020-03-31T14:20:19.5212435Z       at Interface.linereader.on (e:\_1\12\s\node_modules\fable-compiler\dist\index.js:80:30)
2020-03-31T14:20:19.5212904Z       at Interface.emit (events.js:189:13)
2020-03-31T14:20:19.5213381Z       at Socket.onend (readline.js:155:12)
2020-03-31T14:20:19.5213967Z       at Socket.emit (events.js:194:15)
2020-03-31T14:20:19.5214237Z       at endReadableNT (_stream_readable.js:1125:12)
2020-03-31T14:20:19.5214623Z       at process._tickCallback (internal/process/next_tick.js:63:19)
```

```
ERROR in ./project/project.fsproj
2020-03-31T14:05:20.8971271Z   Module build failed (from ./node_modules/fable-loader/index.js):
2020-03-31T14:05:20.8971347Z   Error: The input array was empty.
2020-03-31T14:05:20.8971413Z   Parameter name: array
2020-03-31T14:05:20.8971508Z       at Loader.command.then.data (D:\_2\55\s\node_modules\fable-loader\index.js:98:22)
2020-03-31T14:05:20.8971587Z       at process._tickCallback (internal/process/next_tick.js:68:7)
2020-03-31T14:05:20.8971827Z    @ multi ./project/project.fsproj ./project/style.scss app[0]
```

Is there any particular flag or special logging I can enable to track these down? Any help - even just to debug this further on my part is welcome. I know I can clone, build and fiddle around myself but I hope there is a slightly faster approach/trick :)

### Repro code

Sadly I cannot share and it doesn't reproduce very often anyway. 

### Expected and actual results

Build works, but it fails sometimes, we trigger the build again in that case.

### Related information

* Fable version: `npm show fable-compiler version` or `yarn info fable-compiler version`
```
$ npm show fable-compiler version
2.4.22
```
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
Looking at the error message I assume this is similar to #2043 and it happens during the inter-process communication between .NET and JS. Hopefully these should be gone with Fable 3. Removing the JS process makes debugging easier too.

**Comment by alfonsogarciacaro** [comment]
These errors shouldn't happen in Fable 3 as there's no JSON communication between Fable and Babel anymore.
