### ISSUE TITLE
Strange error with 2.8.2

### ISSUE THREAD

**Issue by AkosLukacs** [fable-compiler/Fable#2038]
### Description

Got this error message after updating to 2.8.2. The code does compile and work with 2.8.1, I don't think I do anything fancy in that file (`./src/Client/Pages/Pages.fs`)

```
ERROR in ./src/Client/Pages/Pages.fs
Module build failed (from ./node_modules/fable-loader/index.js):
Error: You must pass a scope and parentPath unless traversing a Program/File. Instead of that you tried to traverse a Identifier node without passing scope and parentPath.
    at traverse (C:\dev\bla\node_modules\@babel\core\node_modules\@babel\traverse\lib\index.js:57:13)
    at File.buildCodeFrameError (C:\dev\bla\node_modules\@babel\core\lib\transformation\file\file.js:223:31)
    at Scope.checkBlockScopedCollisions (C:\dev\bla\node_modules\@babel\core\node_modules\@babel\traverse\lib\scope\index.js:402:22)
    at Scope.registerBinding (C:\dev\bla\node_modules\@babel\core\node_modules\@babel\traverse\lib\scope\index.js:555:16)
    at Scope.registerDeclaration (C:\dev\bla\node_modules\@babel\core\node_modules\@babel\traverse\lib\scope\index.js:494:12)
    at Object.BlockScoped (C:\dev\bla\node_modules\@babel\core\node_modules\@babel\traverse\lib\scope\index.js:256:12)
    at Object.newFn (C:\dev\bla\node_modules\@babel\core\node_modules\@babel\traverse\lib\visitors.js:220:17)
    at NodePath._call (C:\dev\bla\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:55:20)
    at NodePath.call (C:\dev\bla\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:38:14)
    at NodePath.visit (C:\dev\bla\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:90:31)
    at TraversalContext.visitQueue (C:\dev\bla\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:112:16)
    at TraversalContext.visitSingle (C:\dev\bla\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:84:19)
    at TraversalContext.visit (C:\dev\bla\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:140:19)
    at Function.traverse.node (C:\dev\bla\node_modules\@babel\core\node_modules\@babel\traverse\lib\index.js:84:17)
    at NodePath.visit (C:\dev\bla\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:97:18)
    at TraversalContext.visitQueue (C:\dev\bla\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:112:16)
 @ ./src/Client/Client.fs 2:0-167 49:45-57 49:98-107 50:19-22 58:45-57 58:100-109 59:19-22 67:45-57 67:110-119 68:19-22 75:45-57 75:97-106 76:19-22 81:42-54 81:90-99 84:22-36 103:29-41 104:19-22 112:29-41 113:19-22 121:29-41 122:19-22 129:29-41 130:19-22 135:29-41 140:27-39 140:91-97 140:102-106 146:22-31 146:74-82 222:36-48 222:87-96 223:21-24 225:21-24 234:36-48 234:92-101 235:21-24 250:36-48 250:102-111 251:21-24 263:31-46 307:54-63 329:23-43 334:23-43
 @ ./src/Client/Client.fsproj
 @ multi ./src/Client/Client.fsproj
```

### Repro code

Working on it...

### Expected and actual results

Expected: Compiles with 2.8.2 :)
Actual: Doesn't compile with 2.8.2 :(

### Related information

* Fable version: 2.8.2 and 2.8.1
* Node version: 8.17.0
* Operating system: Win10

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro This is probably related to the changes you made this morning

**Comment by tforkmann** [comment]
Having the same error with 2.8.2

**Comment by MangelMaxime** [comment]
Similar error we had in the past #700

**Comment by MangelMaxime** [comment]
@AkosLukacs @tforkmann 
Version 2.8.3 has been released which revert some of the changes introduces this morning. I didn't test it just saw the release but in theory, it should fix your error.

**Comment by alfonsogarciacaro** [comment]
Sorry! I'm very surprised that the full build (which includes compiling the F# compiler itself with Fable) passed without caching this. I pinpointed it to [this commit](https://github.com/fable-compiler/Fable/commit/c35d0357a7a74d919def7f9812a4eec71334d1b0#) but couldn't find the exact problem, so I just reverted it (it was just a cosmetic feature) and pushed 2.8.3 as @MangelMaxime confirms.

**Comment by forki** [comment]
Friends. Just wanted to say thank you for such quick support

**Comment by tforkmann** [comment]
Thanks guys!
You are awesome!

**Comment by AkosLukacs** [comment]
The new version works on my project too!
Thank you!
