### ISSUE TITLE
QuickTest.fs fails to compile when using lists in the test

### ISSUE THREAD

**Issue by chillitom** [fable-compiler/Fable#2174]
QuickTest.fs looks like an extremely useful way to jump in and begin hacking on the compiler but unfortunately I'm having some issues on the latest `master` branch at this commit https://github.com/fable-compiler/Fable/commit/4456865d7967f3a3abf07ee133b7d12c46fa1494 

Changing the test case in `QuickTest.fs` to `testCase "can use a list" <| fun () -> List.tail [1;2;3] |> equal [2;3]` causes the following compilation error:

```
Parsing ./src/quicktest/QuickTest.fsproj...
[1] fable: Compiled src/quicktest/QuickTest.fs
[1] fable: Compiled .fable/fable-library.2.13.0/String.js
[1] fable: Compiled .fable/fable-library.2.13.0/Date.js
[1] fable: Compiled .fable/fable-library.2.13.0/Long.js
[1] fable: Compiled .fable/fable-library.2.13.0/Int32.js
[1] fable: Compiled .fable/fable-library.2.13.0/lib/long.js
[1] fable: Compiled .fable/fable-library.2.13.0/Util.js
[1] fable: Compiled .fable/fable-library.2.13.0/Decimal.js
[1] fable: Compiled .fable/fable-library.2.13.0/lib/big.js
[1] fable: Compiled .fable/fable-library.2.13.0/RegExp.js
[1] fable: Compiled .fable/fable-library.2.13.0/AsyncBuilder.js
[1] fable: Compiled .fable/fable-library.2.13.0/Async.js
[1] fable: Compiled .fable/fable-library.2.13.0/Option.js
[1] fable: Compiled .fable/fable-library.2.13.0/Types.js
[1] fable: Compiled .fable/fable-library.2.13.0/Seq.js
[1] fable: Skip missing JS file: /home/tom/code/fable/Fable/.fable/fable-library.2.13.0/List.js
[1] fable: Compilation succeeded at 4:48:17 PM (8.796 s)
[1] internal/modules/cjs/loader.js:638
[1]     throw err;
[1]     ^
[1] 
[1] Error: Cannot find module './fable-library.2.13.0/List'
[1]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
[1]     at Module.require (internal/modules/cjs/loader.js:692:17)
[1]     at require (internal/modules/cjs/helpers.js:25:18)
[1]     at Object.<anonymous> (/home/tom/code/fable/Fable/src/quicktest/bin/QuickTest.js:23:13)
[1]     at Module._compile (internal/modules/cjs/loader.js:778:30)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[1]     at Module.load (internal/modules/cjs/loader.js:653:32)
[1]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[1] [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by alfonsogarciacaro** [comment]
Not sure what's the problem but we're not currently working on master now, most of the development is done in `nagareyama` branch in preparation for the next major release. If you're interested it probably makes more sense you try the quicktest there, can you do the following and let me know if it works for you?

```shell
git checkout nagareyama
git clean -xfd     # Just in case there are old artifacts
npm install
npm run build quicktest
```

**Comment by alfonsogarciacaro** [comment]
Quicktest should be working now, please reopen if you still have issues.
