### ISSUE TITLE
Project no longer compiles when going from beta 5 to rc 1

### ISSUE THREAD

**Issue by kerams** [fable-compiler/Fable#2252]
### Description

Unfortunately, I don't have a small repro because this is a moderate size project, but things worked with beta 5 with no issue and broke with upgrade to the release candidate. Maybe just referencing these libraries is enough to trigger the issue (there are no problems reported for my "user" code)? cc @Zaid-Ajaj

```
.fable/Fable.SimpleJson.3.16.2/Json.Converter.fs(1,1): error EXCEPTION: The exception has been reported. This internal exception should now be caught at an error recovery point on the stack. Original message: Exception of type 'FSharp.Compiler.ConstraintSolver+ConstraintSolverError' was thrown.)
.fable/Fable.Remoting.Client.7.0.3/Proxy.fs(1,1): error EXCEPTION: The exception has been reported. This internal exception should now be caught at an error recovery point on the stack. Original message: Exception of type 'FSharp.Compiler.ConstraintSolver+ConstraintSolverError' was thrown.)
```

### Related information

* Fable version: 3.0.0-nagareyama-rc-001
* Windows 10

**Comment by alfonsogarciacaro** [comment]
Damn, I knew something would broke :/ What's the error you get? Can you try using LangVersion preview and referencing FSharp.Core 5?

**Comment by kerams** [comment]
That didn't help and introduced more problems since many Fable packages depend on `FSharp.Core ~> 4`

**Comment by alfonsogarciacaro** [comment]
@kerams Does it happen that your project was already setting `LangVersion=preview`? I'm getting the same error if I try to compile Fable.SimpleJson with LangVersion=preview even if I reference FSharp.Core 5.0. @ncave Do you have an idea of what could be happening? We can try removing/ignoring the `--langversion:preview` option but then users won't be able to use latest features like `nameof`.

**Comment by ncave** [comment]
@alfonsogarciacaro Can we leave it to the users to decide whether they need `--langversion:preview` in their project?
What else changed between beta-005, I might be missing some context, is there a good repro repo we can use?

**Comment by alfonsogarciacaro** [comment]
@ncave It seems that setting the language version to `preview` causes some projects to fail (probably since merging #2240). Fable tests pass but for example if you try to compile fable-standalone with `--langversion:preview` you get multiple errors like the following:

```
/fable/src/fcs-fable/src/fsharp/absil/illib.fs: error EXCEPTION: The exception has been reported. This internal exception should now be caught at an error recovery point on the stack. Original message: Exception of type 'FSharp.Compiler.ConstraintSolver+ConstraintSolverMissingConstraint' was thrown.)
   at FSharp.Compiler.ErrorLogger.ErrorLoggerExtensions.ErrorLogger.Error[b](ErrorLogger x, Exception exn) in /ncave_fsharp/src/fsharp/ErrorLogger.fs:line 397
   at FSharp.Compiler.SourceCodeServices.FSharpExprConvert.GetWitnessArgs(SymbolEnv cenv, ExprTranslationEnv env, ValRef vref, range m, FSharpList`1 tps, FSharpList`1 tyargs) in /ncave_fsharp/src/fsharp/symbols/Exprs.fs:line 499
   at FSharp.Compiler.SourceCodeServices.FSharpExprConvert.ConvModuleValueOrMemberUseLinear$cont@468(SymbolEnv cenv, ExprTranslationEnv env, ValRef vref, FSharpList`1 tyargs, FSharpFunc`2 contF, range m, Int32 numEnclTypeArgs, Boolean isNewObj, FSharpList`1 tps, Boolean isMember, FSharpList`1 curriedArgInfos, FSharpList`1 objArgs, FSharpList`1 curriedArgs, Unit unitVar) in /ncave_fsharp/src/fsharp/symbols/Exprs.fs:line 490
   at FSharp.Compiler.SourceCodeServices.FSharpExprConvert.ConvModuleValueOrMemberUseLinear(SymbolEnv cenv, ExprTranslationEnv env, Expr expr, ValRef vref, ValUseFlag vFlags, FSharpList`1 tyargs, FSharpList`1 curriedArgs, FSharpFunc`2 contF) in /ncave_fsharp/src/fsharp/symbols/Exprs.fs:line 452
   at FSharp.Compiler.SourceCodeServices.FSharpExprConvert.ConvExprPrim(SymbolEnv cenv, ExprTranslationEnv env, Expr expr) in /ncave_fsharp/src/fsharp/symbols/Exprs.fs:line 543
   at FSharp.Compiler.SourceCodeServices.FSharpExprConvert.ConvDecisionTreePrim@1231.Invoke(DecisionTreeCase _arg2, E acc) in /ncave_fsharp/src/fsharp/symbols/Exprs.fs:line 1241
   at FSharp.Compiler.SourceCodeServices.FSharpExprConvert.ConvExprPrimLinear(SymbolEnv cenv, ExprTranslationEnv env, Expr expr, FSharpFunc`2 contF) in /ncave_fsharp/src/fsharp/symbols/Exprs.fs:line 407
   at FSharp.Compiler.SourceCodeServices.FSharpExprConvert.ConvDecisionTreePrim@1231.Invoke(DecisionTreeCase _arg2, E acc) in /ncave_fsharp/src/fsharp/symbols/Exprs.fs:line 1241
   at FSharp.Compiler.SourceCodeServices.FSharpExprConvert.ConvExprPrimLinear(SymbolEnv cenv, ExprTranslationEnv env, Expr expr, FSharpFunc`2 contF) in /ncave_fsharp/src/fsharp/symbols/Exprs.fs:line 407
   at FSharp.Compiler.SourceCodeServices.FSharpExprConvert.ConvExprOnDemand@1288.Invoke(Unit unitVar0) in /ncave_fsharp/src/fsharp/symbols/Exprs.fs:line 1288
   at FSharp.Compiler.SourceCodeServices.FSharpExpr.get_E() in /ncave_fsharp/src/fsharp/symbols/Exprs.fs:line 150
   at FSharp.Compiler.SourceCodeServices.BasicPatterns.|Coerce|_|(FSharpExpr e) in /ncave_fsharp/src/fsharp/symbols/Exprs.fs:line 1374
   at Fable.Transforms.FSharp2Fable.Compiler.transformExpr@279.Invoke(Unit unitVar) in /fable/src/Fable.Transforms/FSharp2Fable.fs:line 372
   at MonadicTrampoline.run[a](Thunk`1 _arg1) in /fable/src/Fable.Transforms/MonadicTrampoline.fs:line 8
   at Fable.Transforms.FSharp2Fable.Compiler.transformMemberFunction(IFableCompiler com, Context ctx, Boolean isPublic, String name, String fullDisplayName, FSharpMemberOrFunctionOrValue memb, FSharpList`1 args, FSharpExpr body) in /fable/src/Fable.Transforms/FSharp2Fable.fs:line 966
   at Fable.Transforms.FSharp2Fable.Compiler.transformMemberFunctionOrValue(IFableCompiler com, Context ctx, FSharpMemberOrFunctionOrValue memb, FSharpList`1 args, FSharpExpr body) in /fable/src/Fable.Transforms/FSharp2Fable.fs:line 1009
   at Fable.Transforms.FSharp2Fable.Compiler.transformMemberDecl(FableCompiler com, Context ctx, FSharpMemberOrFunctionOrValue memb, FSharpList`1 args, FSharpExpr body) in /fable/src/Fable.Transforms/FSharp2Fable.fs:line 1062
   at Microsoft.FSharp.Primitives.Basics.List.collectToFreshConsTail[T,TResult](FSharpFunc`2 f, FSharpList`1 list, FSharpList`1 cons) in /ncave_fsharp/src/fsharp/FSharp.Core/local.fs:line 439
   at Microsoft.FSharp.Primitives.Basics.List.collect[T,TResult](FSharpFunc`2 f, FSharpList`1 list) in /ncave_fsharp/src/fsharp/FSharp.Core/local.fs:line 447
   at Microsoft.FSharp.Primitives.Basics.List.collectToFreshConsTail[T,TResult](FSharpFunc`2 f, FSharpList`1 list, FSharpList`1 cons) in /ncave_fsharp/src/fsharp/FSharp.Core/local.fs:line 439
   at Microsoft.FSharp.Primitives.Basics.List.collect[T,TResult](FSharpFunc`2 f, FSharpList`1 list) in /ncave_fsharp/src/fsharp/FSharp.Core/local.fs:line 447
   at Fable.Transforms.FSharp2Fable.Compiler.transformFile(Compiler com) in /fable/src/Fable.Transforms/FSharp2Fable.fs:line 1260
   at Fable.Cli.Main.Util.compileFile@154-1.Invoke(Unit unitVar) in /fable/src/Fable.Cli/Main.fs:line 154
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in /ncave_fsharp/src/fsharp/FSharp.Core/async.fs:line 386
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in /ncave_fsharp/src/fsharp/FSharp.Core/async.fs:line 105
```

**Comment by kerams** [comment]
>Does it happen that your project was already setting LangVersion=preview

That is correct. It compiles when I remove it.

However, when I now make use of UMX and a string with UoM, I see `error FABLE: Cannot resolve trait call cast - Inline call from` in a couple of places, which is not there with the preview set. This might be a different issue altogether though.

**Comment by ncave** [comment]
@alfonsogarciacaro Thanks, that helped. Here is a small repro that breaks it:
```fs
let test x =
    match x with
    | [| |] -> x
    | _ -> x
```
I will open an issue in `dotnet/fsharp`, in the mean time I've patched the [service_slim](https://github.com/ncave/fsharp/tree/service_slim) branch to ignore errors in `GetWitnessArgs`, you can rebuild with it if you don't want to wait for this issue to be fixed in `dotnet/fsharp`.

**Comment by alfonsogarciacaro** [comment]
Thanks a lot @ncave! The patch is super helpful because I rushed the announcement of the release candidate 😅 so it's better to publish a fix as soon as possible. In the latest release I'm also setting `--langversion:preview` by default because now Fable relies on the witness feature and also to avoid having to test against a matrix of compiler versions.

@kerams The issues are actually related, Fable now uses witnesses to resolve SRTP, and they were only enabled when activating preview. This should be fixed in the latest release.

**Comment by kerams** [comment]
The project compiles with rc 2, but now I see warnings like https://github.com/fable-compiler/Fable/issues/1962 (`export 'attributeValue$reflection' (imported as 'attributeValue$reflection') was not found in`) and the whole thing crashes at runtime somewhere in Fable.SimpleJson/Remoting.

**Comment by alfonsogarciacaro** [comment]
Hmm, I tried the Fable.Remoting tests with Fable rc2 and they passed. Would it be possible to reproduce this somehow? What's that `AttributeValue`? Does it come from code shared between server and client?

**Comment by kerams** [comment]
```fsharp
[<Measure>]
type attributeValue

type AttributeValue = string<attributeValue>
```

Try using this in one of the Remothing functions. If you can't reproduce, I'll try to extract if from my project.

**Comment by alfonsogarciacaro** [comment]
I think I found the issue. I can reproduce it like this:

```fsharp
open FSharp.UMX
open FSharp.Reflection

[<Measure>]
type attributeValue

type AttributeValue = string<attributeValue>

type R = { Foo: AttributeValue }

let recordValueFields = FSharpType.GetRecordFields typeof<R>
```

I think witnesses allowed us to use FSharp.UMX without referencing the type which fixed #1962. But the problem is still there and because Fable.Remoting does try to access the type info it fails at runtime. Unfortunately I couldn't find a way to access the abbreviated type in a `MeasureAnnotatedAbbreviation` in FCS (there is an `UnqualifiedType` private field though) so I think I'll have to hardcode FSharp.UMX types as discussed before.

**Comment by kerams** [comment]
I see, thank you.

**Comment by alfonsogarciacaro** [comment]
Can you please try with RC 3?

**Comment by kerams** [comment]
Fantastic, all good now.

**Comment by alfonsogarciacaro** [comment]
Finally! Thanks a lot for checking 👍

**Comment by alfonsogarciacaro** [comment]
@TerenceHinrichsen What version of Fable are you using? This issue should already be fixed, we [have a test for it](https://github.com/fable-compiler/Fable/blob/906bdcd6b3961eca1716b2556dbcb37c9c0a66bd/tests/Main/MiscTests.fs#L434-L445).

If you're running an old version, can you please run `dotnet tool update fable` and try again?

**Comment by TerenceHinrichsen** [comment]
I must just say, I will NEVER get used to this amazing F# community! 
That was spot on @alfonsogarciacaro  - I was on 3.1.15 - now on 3.4.5. Really sorry to have bothered with this, but THANK YOU for your response!
