### ISSUE TITLE
Computation Expression tests fail when upgrading from Fable 2 to 3

### ISSUE THREAD

**Issue by TheAngryByrd** [fable-compiler/Fable#2438]
### Description

I'm working on updating `FsToolkit.ErrorHandling` from Fable 2 to Fable 3.  However when I'm getting test failures in my some of my computation expression tests where as they all passed before in Fable 2. The tests in particular are the `combine/zero/delay/run Tests` which test a computation expressions `Combine`, `Zero`, `Delay`, and `Run` members.

### Repro code

https://github.com/demystifyfp/FsToolkit.ErrorHandling/pull/129 is the PR you can pull to view this behavior.

run `npm test` (may have to do a `./build.sh` to get all bootstraped with npm/dotnet restores)

### Expected and actual results

<details>
    <summary>Included is the error messages I'm getting with these</summary>

```
  351 passing (164ms)
  5 failing

  1) All Tests
       Result CE Tests
         ResultCE combine/zero/delay/run Tests
           Zero/Combine/Delay/Run:
     TypeError: Cannot read property 'tag' of undefined
      at Result_Bind (file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/Choice.js:39:16)
      at ResultCE_ResultBuilder__Combine_71B5E353 (file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/src/FsToolkit.ErrorHandling/ResultCE.js:32:12)
      at file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/ResultCE.js:341:85
      at Context.<anonymous> (file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/ResultCE.js:341:322)
      at processImmediate (node:internal/timers:464:21)

  2) All Tests
       Option CE tests
         CE Tests
           Zero/Combine/Delay/Run:
     Error: Should be ok
      at assertEqual (file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/Util.js:88:29)
      at Context.<anonymous> (file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/OptionCE.js:141:9)
      at processImmediate (node:internal/timers:464:21)

  3) All Tests
       Async Option CE tests
         CE Tests
           Zero/Combine/Delay/Run:
     TypeError: computation is not a function
      at file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/AsyncBuilder.js:80:9
      at file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/AsyncBuilder.js:70:17
      at file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/AsyncBuilder.js:107:50
      at file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/AsyncBuilder.js:70:17
      at file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/AsyncBuilder.js:107:50
      at file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/AsyncBuilder.js:70:17
      at file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/AsyncBuilder.js:80:9
      at file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/AsyncBuilder.js:70:17
      at file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/AsyncBuilder.js:107:50
      at file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/AsyncBuilder.js:70:17
      at file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/Async.js:66:9
      at file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/AsyncBuilder.js:70:17
      at file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/AsyncBuilder.js:80:9
      at file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/AsyncBuilder.js:70:17
      at file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/AsyncBuilder.js:107:50
      at file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/AsyncBuilder.js:70:17
      at startWithContinuations (file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/Async.js:109:5)
      at start (file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/Async.js:98:12)
      at startImmediate (file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/Async.js:101:12)
      at Mocha_configureAsyncTest (file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/Fable.Mocha.2.8.0/Mocha.fs.js:574:5)
      at Context.<anonymous> (file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/Fable.Mocha.2.8.0/Mocha.fs.js:626:25)
      at processImmediate (node:internal/timers:464:21)

  4) All Tests
       AsyncResultCETests
         AsyncResultCE combine/zero/delay/run Tests
           Zero/Combine/Delay/Run:
     TypeError: computation is not a function
      at file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/AsyncBuilder.js:80:9
      at file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/AsyncBuilder.js:70:17
      at file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/AsyncBuilder.js:107:50
      at file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/AsyncBuilder.js:70:17
      at file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/AsyncBuilder.js:107:50
      at file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/AsyncBuilder.js:70:17
      at file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/AsyncBuilder.js:80:9
      at file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/AsyncBuilder.js:70:17
      at file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/AsyncBuilder.js:107:50
      at file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/AsyncBuilder.js:70:17
      at file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/Async.js:66:9
      at file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/AsyncBuilder.js:70:17
      at file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/AsyncBuilder.js:80:9
      at file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/AsyncBuilder.js:70:17
      at file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/AsyncBuilder.js:107:50
      at file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/AsyncBuilder.js:70:17
      at startWithContinuations (file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/Async.js:109:5)
      at start (file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/Async.js:98:12)
      at startImmediate (file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/Async.js:101:12)
      at Mocha_configureAsyncTest (file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/Fable.Mocha.2.8.0/Mocha.fs.js:574:5)
      at Context.<anonymous> (file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/Fable.Mocha.2.8.0/Mocha.fs.js:626:25)
      at processImmediate (node:internal/timers:464:21)

  5) All Tests
       Validation CE Tests
         ValidationCE combine/zero/delay/run Tests
           Zero/Combine/Delay/Run:
     TypeError: Cannot read property 'tag' of undefined
      at Result_Bind (file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/.fable/fable-library.3.1.15/Choice.js:39:16)
      at Validation_bind (file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/src/FsToolkit.ErrorHandling/Validation.js:88:12)
      at ValidationCE_ValidationBuilder__Combine_68A899F3 (file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/src/FsToolkit.ErrorHandling/ValidationCE.js:35:12)
      at file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/ValidationCE.js:494:172
      at ValidationCE_ValidationBuilder__Run_Z29103BAD (file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/src/FsToolkit.ErrorHandling/ValidationCE.js:31:12)
      at Context.<anonymous> (file:///Users/jimmybyrd/Documents/repos/public/demystifyfp/FsToolkit.ErrorHandling/dist/tests/ValidationCE.js:494:22)
      at processImmediate (node:internal/timers:464:21)
```

</details>

### Related information

<details>
    <summary>dotnet fable --version</summary>

```
Fable: F# to JS compiler 3.1.15
Thanks to the contributor! @zpodlovics
3.1.15
```

</details>

<details>
    <summary>dotnet --info</summary>
    
```
.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.201/

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  3.1.406 [/usr/local/share/dotnet/sdk]
  3.1.407 [/usr/local/share/dotnet/sdk]
  5.0.103 [/usr/local/share/dotnet/sdk]
  5.0.201 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

</details>

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for the code to reproduce and sorry for taking so long to look into this @TheAngryByrd. Seems it was because JS sequence expressions weren't being correctly printed between parentheses. I'm surprised this hasn't surfaced before but hopefully it should be fixed now. Could you please update to fable 3.2.4 and see if the tests pass now? I checked by myself and they did :)

**Comment by TheAngryByrd** [comment]
Thanks a ton! I'll give it a shot tonight
