### ISSUE TITLE
Fable 3.2.14+ breaks native ESM modules support

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#2549]
### Description

```
file:///home/maximemangel/Documents/Workspaces/Github/MangelMaxime/Nacara/src/Nacara/dist/.fable/Fable.Elmish.3.1.0/prelude.fs.js:3
import { add } from "../fable-library.3.3.0/Observable.js";
         ^^^
SyntaxError: Named export 'add' not found. The requested module '../fable-library.3.3.0/Observable.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '../fable-library.3.3.0/Observable.js';
const { add } = pkg;

    at ModuleJob._instantiate (internal/modules/esm/module_job.js:120:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:165:5)
    at async Loader.import (internal/modules/esm/loader.js:177:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
[nodemon] app crashed - waiting for file changes before starting...
```

### Repro code

I don't have a simple reproduction code available but I encounter this issue with Nacara.

1. Clone https://github.com/MangelMaxime/Nacara
2. Change the Fable version in `.config/dotnet-tools.json` to `3.2.14` or `3.3.0`
3. `dotnet tool restore`
2. `make setup-dev`
3. `make watch`
4. See the error happening

### Expected and actual results

Please provide the expected and actual results.

### Related information

* Fable version: `dotnet fable --version`
* Operating system

**Comment by alfonsogarciacaro** [comment]
That's interesting. I don't think there's been any change about ESM in the recent versions. I can see that you're using the `esm` loader, are you using the same version as before?

**Comment by alfonsogarciacaro** [comment]
Or... Maybe it's because we added a package.json recently to fable-library and this confuses esm? Does it work if you add `type: module` to the package.json with fable-library dir?

**Comment by MangelMaxime** [comment]
I don't use `esm` loader anymore there are bugs in it that are problematic and the maintainer doesn't seems to be working on it anymore.

Instead, I use `type: module` to use [Pure ESM package](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) which are supported by Node.js 12.20, 14.14, or 16.0.

Adding `type: "module"` to both the `fable-library/package.json` fixed this issue for my project.

So we need to add it to the `package.json`.

I am not sure what the behaviour of `Node.js` will be if people don't use pure ESM package in their project.

Should we make it the default? Should we add an option to Fable CLI to allow the user choose which `module` type he wants to set for the package.json?

**Comment by alfonsogarciacaro** [comment]
I'm assuming it should be safe to use `type: module` only in fable-library because if I'm not mistaken node will only consider ES modules files within that hierarchy. If we use `type: commonjs`, it may get confused because the files are actually ES modules (I think this is what happened here).

I don't remember exactly, but I think the problem of setting `type: module` in the repo root is that it also affects dependencies within node_modules, and it can also happen that some Fable libs include JS files using commonjs.

**Comment by MangelMaxime** [comment]
> I don't remember exactly, but I think the problem of setting type: module in the repo root is that it also affects dependencies within node_modules, and it can also happen that some Fable libs include JS files using commonjs.

You are right, setting it from the root seems to have this behaviour. But I think the ecosystem should move to ESM slowly as it simplify and improve a lot of stuff.

That being said, it is up to the user to decide if he wants to use only ESM modules or not. If he doesn't and if the `esm` loader bugs doesn't impact it then he can choose to stay with `commonjs` modules.

If he encounter library using commonjs File in it, he can ask the maintainer to update the library.

**Comment by alfonsogarciacaro** [comment]
At the end adding `type: module` broke CI, so I just removed the package.json from fable-library :/

**Comment by MangelMaxime** [comment]
When testing it locally I had a different error than the one from the CI... 

```
/home/maximemangel/Documents/Workspaces/Github/Fable/Fable> npm run mocha -- build/tests/DefineConstants/DebugWithExtraDefines -r esm --reporter dot -t 10000

> mocha
> mocha "build/tests/DefineConstants/DebugWithExtraDefines" "-r" "esm" "--reporter" "dot" "-t" "10000"


TypeError: Invalid host defined options
    at formattedImport (/home/maximemangel/Documents/Workspaces/Github/Fable/Fable/node_modules/mocha/lib/esm-utils.js:7:31)
    at Object.exports.requireOrImport (/home/maximemangel/Documents/Workspaces/Github/Fable/Fable/node_modules/mocha/lib/esm-utils.js:45:14)
    at Object.exports.loadFilesAsync (/home/maximemangel/Documents/Workspaces/Github/Fable/Fable/node_modules/mocha/lib/esm-utils.js:55:34)
    at Mocha.loadFilesAsync (/home/maximemangel/Documents/Workspaces/Github/Fable/Fable/node_modules/mocha/lib/mocha.js:473:19)
    at singleRun (/home/maximemangel/Documents/Workspaces/Github/Fable/Fable/node_modules/mocha/lib/cli/run-helpers.js:125:15)
    at exports.runMocha (/home/maximemangel/Documents/Workspaces/Github/Fable/Fable/node_modules/mocha/lib/cli/run-helpers.js:190:10)
    at Object.exports.handler (/home/maximemangel/Documents/Workspaces/Github/Fable/Fable/node_modules/mocha/lib/cli/run.js:362:11)
    at /home/maximemangel/Documents/Workspaces/Github/Fable/Fable/node_modules/yargs/build/index.cjs:443:71
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:60:5)
    at /home/maximemangel/Documents/Workspaces/Github/Fable/Fable/node_modules/esm/esm.js:1:34535
    at /home/maximemangel/Documents/Workspaces/Github/Fable/Fable/node_modules/esm/esm.js:1:34176
    at process.<anonymous> (/home/maximemangel/Documents/Workspaces/Github/Fable/Fable/node_modules/esm/esm.js:1:34506)
    at Function.<anonymous> (/home/maximemangel/Documents/Workspaces/Github/Fable/Fable/node_modules/esm/esm.js:1:296856)
    at Function.<anonymous> (/home/maximemangel/Documents/Workspaces/Github/Fable/Fable/node_modules/esm/esm.js:1:296555)
    at Function.<anonymous> (/home/maximemangel/Documents/Workspaces/Github/Fable/Fable/node_modules/esm/esm.js:1:284879)
    at Object.apply (/home/maximemangel/Documents/Workspaces/Github/Fable/Fable/node_modules/esm/esm.js:1:199341)
    at internal/main/run_main_module.js:17:47
System.Exception: Process exited with code 1
   at FSI_0001.PublishUtils.Platform.Process@239.FSI_0001.PublishUtils.IProcess.Run(String workingDir, String exePath, String[] args)
   at FSI_0002.testDefineConstants()
   at FSI_0002.test()
   at <StartupCode$FSI_0002>.$FSI_0002.main@()
Stopped due to error
```

So I wasn't able to debug the CI failure correctly.

However, I was able to have the tests running on my computer by doing these changes:

https://github.com/fable-compiler/Fable/commit/6002775ae4bfe857deffa8102f33a0d29bbab8b6

This require the CI to use one of the Node.js version that support native ESM modules.

**Comment by alfonsogarciacaro** [comment]
Thanks @MangelMaxime! After some fixes to the compiler_js package CI is running :tada: It probably needs more adjustment to actually release the fable_compiler_js package, but we can do those later.

**Comment by MangelMaxime** [comment]
Thank you @alfonsogarciacaro I will test it when the new version is released as we know that Nacara project is a good candidate to test this changes.
