### ISSUE TITLE
Fable cannot find operator from separate file.

### ISSUE THREAD

**Issue by IanManske** [fable-compiler/Fable#2880]
### Description

I've found an issue regarding operators. Sometimes when using a `static member` operator defined in a separate file, the operator fails to get imported correctly in the outputted JS. If the operator is marked as `static member inline`, then the Fable Compiler crashes because it fails to find the operator (see below). Hopefully I'm not missing something obvious.

### Repo code
`Main.fs`:
```fsharp
module Main

open Fable.Core

[<Erase>]
type Vector2<[<Measure>] 'u> = Vector2 of x: float<'u> * y: float<'u> with

  static member ( + ) (Vector2(ax, ay), Vector2(bx, by)) = Vector2(ax + bx, ay + by)

  static member ( * ) (scalar, Vector2(x, y)) = Vector2(scalar * x, scalar * y)

let lerp x (alpha: float) (delta: Vector2<_>) = x + alpha * delta
```

`Alt.fs`:
```fsharp
module Alt

open Main

let lerp x (alpha: float) (delta: Vector2<_>) = x + alpha * delta
```

Here's a repo with all the code for this issue: [NonexistentOperator](https://github.com/IanManske/NonexistentOperator)

### Expected and actual results

From the outputted `Main.js`:
```javascript
export function Vector2_op_Addition_Z5CB0E160(_arg1, _arg2) {
    return [_arg1[0] + _arg2[0], _arg1[1] + _arg2[1]];
}

export function Vector2_op_Multiply_7A82AB7(scalar, _arg3) {
    return [scalar * _arg3[0], scalar * _arg3[1]];
}

export function lerp(x, alpha, delta) {
    return Vector2_op_Addition_Z5CB0E160(x, Vector2_op_Multiply_7A82AB7(alpha, delta));
}
```
The `lerp` function above is expected, but in `Alt.js` a nonexistent multiply function is imported:
```javascript
import { Vector2_op_Multiply_66BD8A21, Vector2_op_Addition_Z5CB0E160 } from "./Main.js";

export function lerp(x, alpha, delta) {
    return Vector2_op_Addition_Z5CB0E160(x, Vector2_op_Multiply_66BD8A21(alpha, delta));
}
```
What I find weird is that the correct addition function is imported, but the multiply function is not correct.

If the operators are marked as `static member inline`, then the Fable compiler crashes:
```
Started Fable compilation...
Fable compilation finished in 999ms

./src/Alt.fs(1,1): error EXCEPTION: Cannot find inline member: Main.Vector2_op_Multiply_66BD8A21
   at Fable.Transforms.State.CompilerImpl.Fable.Compiler.GetInlineExpr(String memberUniqueName) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\State.fs:line 259
   at Fable.Transforms.FSharp2Fable.Util.inlineExpr(IFableCompiler com, Context ctx, FSharpOption`1 r, Type t, FSharpList`1 genArgs, FSharpOption`1 callee, CallInfo info, String membUniqueName) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\FSharp2Fable.Util.fs:line 1831
   at Fable.Transforms.FSharp2Fable.Util.|Inlined|_|(IFableCompiler com, Context ctx, FSharpOption`1 r, Type t, FSharpList`1 genArgs, FSharpOption`1 callee, CallInfo info, FSharpMemberOrFunctionOrValue memb) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\FSharp2Fable.Util.fs:line 1880
   at Fable.Transforms.FSharp2Fable.Util.makeCallWithArgInfo(IFableCompiler com, Context ctx, FSharpOption`1 r, Type typ, FSharpList`1 genArgs, FSharpOption`1 callee, FSharpMemberOrFunctionOrValue memb, CallInfo callInfo) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\FSharp2Fable.Util.fs:line 1911
   at Fable.Transforms.FSharp2Fable.Compiler.transformExpr@701-36.Invoke(Context ctx) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\FSharp2Fable.fs:line 701
   at MonadicTrampoline.run[a](Thunk`1 _arg1) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\MonadicTrampoline.fs:line 8
   at MonadicTrampoline.Bind@16.Invoke(Unit unitVar0) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\MonadicTrampoline.fs:line 16
   at MonadicTrampoline.run[a](Thunk`1 _arg1) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\MonadicTrampoline.fs:line 8
   at MonadicTrampoline.Bind@16.Invoke(Unit unitVar0) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\MonadicTrampoline.fs:line 16
   at MonadicTrampoline.run[a](Thunk`1 _arg1) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\MonadicTrampoline.fs:line 8
   at MonadicTrampoline.Bind@16.Invoke(Unit unitVar0) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\MonadicTrampoline.fs:line 16
   at MonadicTrampoline.run[a](Thunk`1 _arg1) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\MonadicTrampoline.fs:line 8
   at MonadicTrampoline.Bind@16.Invoke(Unit unitVar0) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\MonadicTrampoline.fs:line 16
   at MonadicTrampoline.run[a](Thunk`1 _arg1) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\MonadicTrampoline.fs:line 8
   at MonadicTrampoline.Bind@16.Invoke(Unit unitVar0) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\MonadicTrampoline.fs:line 16
   at MonadicTrampoline.run[a](Thunk`1 _arg1) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\MonadicTrampoline.fs:line 8
   at Fable.Transforms.FSharp2Fable.Compiler.transformMemberFunction(IFableCompiler com, Context ctx, Boolean isPublic, String name, String fullDisplayName, FSharpMemberOrFunctionOrValue memb, FSharpList`1 args, FSharpExpr body) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\FSharp2Fable.fs:line 1215
   at Fable.Transforms.FSharp2Fable.Compiler.transformMemberFunctionOrValue(IFableCompiler com, Context ctx, FSharpMemberOrFunctionOrValue memb, FSharpList`1 args, FSharpExpr body) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\FSharp2Fable.fs:line 1263
   at Fable.Transforms.FSharp2Fable.Compiler.transformMemberDecl(FableCompiler com, Context ctx, FSharpMemberOrFunctionOrValue memb, FSharpList`1 args, FSharpExpr body) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\FSharp2Fable.fs:line 1340
   at Fable.Transforms.FSharp2Fable.Compiler.transformFile(Compiler com) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\FSharp2Fable.fs:line 1814
   at Fable.Cli.Main.Util.compileFile@178-1.Invoke(Unit unitVar) in C:\Users\alfon\repos\Fable\src\Fable.Cli\Main.fs:line 178
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in C:\Users\alfon\repos\fsharp\src\fsharp\FSharp.Core\async.fs:line 447
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in C:\Users\alfon\repos\fsharp\src\fsharp\FSharp.Core\async.fs:line 104
Compilation failed
```

### Related information

* Fable version: 3.7.11
* Operating system: (Arch) Linux, also tested in a Windows 10 VM with the same results.

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for the detailed report and the code to reproduce @IanManske! Sorry for the late reply, this seems to be related with the Measure. If we remove it works, though I'm a bit puzzled about why it works differently depending on the file.

Now that the problem is spotted, hopefully it's not difficult to fix 😸 I'll keep you posted.

**Comment by IanManske** [comment]
Ok great, thanks! I'm actually kind of curious now as to what could be causing this - seems like a weird bug.
