### ISSUE TITLE
Fable does not support unsigned units of measure

### ISSUE THREAD

**Issue by sonicbhoc** [fable-compiler/Fable#2955]
### Description

It does not appear the Fable has implemented [FS-1091](https://github.com/fsharp/fslang-design/blob/main/FSharp-6.0/FS-1091-Extend-Units-of-Measure.md).

When using an unsigned literal with a unit of measure, Fable throws an exception when compiling:

```
client: .\..\Shared\CodeModule.fs(1,1): error EXCEPTION: Unexpected type DeclaredType
client:   ({ FullName = "Microsoft.FSharp.Core.uint`1"
client:      Path = CoreAssemblyName "FSharp.Core" },
client:    [DeclaredType
client:       ({ FullName = "GDC.Shared.Units.hr"
client:          Path =
client:           SourcePath "C:/Users/cchristie/source/repos/qe/src/Shared/Units.fs" },
client:        [])]) for literal 20 (System.UInt32)
client:    at Fable.Transforms.Replacements.makeTypeConst$cont@329(FSharpOption`1 r, Type typ, Object value, Unit unitVar) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\Replacements.fs:line 367
client:    at Fable.Transforms.Replacements.makeTypeConst(Compiler com, FSharpOption`1 r, Type typ, Object value) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\Replacements.fs:line 334
client:    at Fable.Transforms.FSharp2Fable.Compiler.transformExpr@410.Invoke(Unit unitVar) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\FSharp2Fable.fs:line 791
client:    at MonadicTrampoline.run[a](Thunk`1 _arg1) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\MonadicTrampoline.fs:line 8
client:    at MonadicTrampoline.Bind@16.Invoke(Unit unitVar0) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\MonadicTrampoline.fs:line 16
client:    at MonadicTrampoline.run[a](Thunk`1 _arg1) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\MonadicTrampoline.fs:line 8
client:    at MonadicTrampoline.Bind@16.Invoke(Unit unitVar0) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\MonadicTrampoline.fs:line 16
client:    at MonadicTrampoline.run[a](Thunk`1 _arg1) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\MonadicTrampoline.fs:line 8
client:    at MonadicTrampoline.Bind@16.Invoke(Unit unitVar0) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\MonadicTrampoline.fs:line 16
client:    at MonadicTrampoline.run[a](Thunk`1 _arg1) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\MonadicTrampoline.fs:line 8
client:    at MonadicTrampoline.Bind@16.Invoke(Unit unitVar0) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\MonadicTrampoline.fs:line 16
client:    at MonadicTrampoline.run[a](Thunk`1 _arg1) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\MonadicTrampoline.fs:line 8
client:    at MonadicTrampoline.Bind@16.Invoke(Unit unitVar0) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\MonadicTrampoline.fs:line 16
client: Watching ..
client:    at MonadicTrampoline.run[a](Thunk`1 _arg1) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\MonadicTrampoline.fs:line 8
client:    at Fable.Transforms.FSharp2Fable.Compiler.transformMemberFunction(IFableCompiler com, Context ctx, Boolean isPublic, String name, String fullDisplayName, FSharpMemberOrFunctionOrValue memb, FSharpList`1 args, FSharpExpr body) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\FSharp2Fable.fs:line 1239
client:    at Fable.Transforms.FSharp2Fable.Compiler.transformMemberFunctionOrValue(IFableCompiler com, Context ctx, FSharpMemberOrFunctionOrValue memb, FSharpList`1 args, FSharpExpr body) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\FSharp2Fable.fs:line 1265
client:    at Fable.Transforms.FSharp2Fable.Compiler.transformMemberDecl(FableCompiler com, Context ctx, FSharpMemberOrFunctionOrValue memb, FSharpList`1 args, FSharpExpr body) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\FSharp2Fable.fs:line 1342
client:    at Fable.Transforms.FSharp2Fable.Compiler.transformDeclarations@1391.Invoke(FSharpImplementationFileDeclaration fsDecl) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\FSharp2Fable.fs:line 1416
client:    at Microsoft.FSharp.Primitives.Basics.List.collectToFreshConsTail[T,TResult](FSharpFunc`2 f, FSharpList`1 list, FSharpList`1 cons) in C:\Users\alfon\repos\fsharp\src\fsharp\FSharp.Core\local.fs:line 435
client:    at Microsoft.FSharp.Primitives.Basics.List.collect[T,TResult](FSharpFunc`2 f, FSharpList`1 list) in C:\Users\alfon\repos\fsharp\src\fsharp\FSharp.Core\local.fs:line 443
client:    at Fable.Transforms.FSharp2Fable.Compiler.transformFile(Compiler com) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\FSharp2Fable.fs:line 1719
client:    at Fable.Cli.Main.Util.compileFile@178-1.Invoke(Unit unitVar) in C:\Users\alfon\repos\Fable\src\Fable.Cli\Main.fs:line 178
client:    at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in C:\Users\alfon\repos\fsharp\src\fsharp\FSharp.Core\async.fs:line 447
client:    at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in C:\Users\alfon\repos\fsharp\src\fsharp\FSharp.Core\async.fs:line 104
```

### Repro code

```
[<Measure>]
type custom

type Test<[<Measure>] 'u>
    | Value of uint<'u>
    static member Default =
        Value 20u<custom>
```

### Expected and actual results
Expected result: Javascript code is generated.

Actual result: Exception thrown.

### Related information

* Fable version: 3.7.16
* Operating system: Windows 10 20H2

**Comment by alfonsogarciacaro** [comment]
Ah, I didn't realize this was already in the language. Units of measure are a bit tricky because they need to be hard-coded, I will add them 👍

**Comment by sonicbhoc** [comment]
Thank you! my entire model is unsigned, and having to convert everything to signed just makes massive holes everywhere that require extra validation logic.
