### ISSUE TITLE
My project fails to compile with 4.0.0-theta-012

### ISSUE THREAD

**Issue by OnurGumus** [fable-compiler/Fable#3244]
### Description

My project compiles fine with 4.0.0-theta-011 but fails with 4.0.0-theta-012 as below
```
Parsing Client/Client.fsproj...
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
   at System.Text.RegularExpressions.Regex.Split(String input)
   at Fable.Cli.ProjectCracker.getProjectOptionsFromProjectFile@397.Invoke(CrackerOptions opts, String projFile) in /Users/dbrattli/Developer/Github/Fable/src/Fable.Cli/ProjectCracker.fs:line 422
   at Fable.Cli.ProjectCracker.easyCrack(CrackerOptions opts, IDictionary`2 dllRefs, String projFile) in /Users/dbrattli/Developer/Github/Fable/src/Fable.Cli/ProjectCracker.fs:line 453
   at Fable.Cli.ProjectCracker.crackProjects@478.Invoke(FSharpList`1 acc, String projFile) in /Users/dbrattli/Developer/Github/Fable/src/Fable.Cli/ProjectCracker.fs:line 480
   at Microsoft.FSharp.Collections.ListModule.Fold[T,TState](FSharpFunc`2 folder, TState state, FSharpList`1 list) in /home/dev/Projects/fsharp/src/FSharp.Core/list.fs:line 295
   at Fable.Cli.ProjectCracker.getCrackedProjectsFromMainFsproj(CrackerOptions opts) in /Users/dbrattli/Developer/Github/Fable/src/Fable.Cli/ProjectCracker.fs:line 486
   at Fable.Cli.ProjectCracker.retry@504(CrackerOptions opts, DateTime retryUntil, Unit unitVar0) in /Users/dbrattli/Developer/Github/Fable/src/Fable.Cli/ProjectCracker.fs:line 506
   at Fable.Cli.ProjectCracker.retryGetCrackedProjects(CrackerOptions opts) in /Users/dbrattli/Developer/Github/Fable/src/Fable.Cli/ProjectCracker.fs:line 515
   at Fable.Cli.ProjectCracker.getFullProjectOpts(CrackerOptions opts) in /Users/dbrattli/Developer/Github/Fable/src/Fable.Cli/ProjectCracker.fs:line 732
   at Fable.Cli.Main.Init@339.Invoke(Unit unitVar0) in /Users/dbrattli/Developer/Github/Fable/src/Fable.Cli/Main.fs:line 340
   at Fable.Cli.Performance.measure[a](FSharpFunc`2 f) in /Users/dbrattli/Developer/Github/Fable/src/Fable.Cli/Util.fs:line 690
   at Fable.Cli.Main.ProjectCracked.Init(CliArgs cliArgs) in /Users/dbrattli/Developer/Github/Fable/src/Fable.Cli/Main.fs:line 339
   at Fable.Cli.Main.compilationCycle@736.Invoke(Unit unitVar) in /Users/dbrattli/Developer/Github/Fable/src/Fable.Cli/Main.fs:line 741
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in /home/dev/Projects/fsharp/src/FSharp.Core/async.fs:line 510
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in /home/dev/Projects/fsharp/src/FSharp.Core/async.fs:line 112
--- End of stack trace from previous location ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in /home/dev/Projects/fsharp/src/FSharp.Core/async.fs:line 454
   at Microsoft.FSharp.Control.AsyncPrimitives.QueueAsyncAndWaitForResultSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout) in /home/dev/Projects/fsharp/src/FSharp.Core/async.fs:line 1140
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in /home/dev/Projects/fsharp/src/FSharp.Core/async.fs:line 1167
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in /home/dev/Projects/fsharp/src/FSharp.Core/async.fs:line 1511
   at Fable.Cli.Entry.Run@214-2.Invoke(Unit _arg5) in /Users/dbrattli/Developer/Github/Fable/src/Fable.Cli/Entry.fs:line 297
   at Fable.Cli.Entry.main@386.Invoke(Tuple`2 _arg2) in /Users/dbrattli/Developer/Github/Fable/src/Fable.Cli/Entry.fs:line 392
   at Fable.Cli.Entry.main(String[] argv) in /Users/dbrattli/Developer/Github/Fable/src/Fable.Cli/Entry.fs:line 384
```

### Related information

* Fable version: 4.0.0-theta-012 
* Operating system : MacOS

**Comment by alfonsogarciacaro** [comment]
Thanks for reporting @OnurGumus! We're using Buildalyzer since theta-012 to fix #3182 but it may happen that I'm not using it correctly or covering all corner cases. Would it be possible to share more info about your project or even sharing the .fsproj file? Are you targeting multiple frameworks? What's the dotnet sdk version?

**Comment by OnurGumus** [comment]
Sorry it wasn't macos but running under ubuntu via docker.
.NET SDK Version:   6.0.402
proj file
```
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Lit.React.fs" />
    <Compile Include="AppContnext.fs" />
    <Compile Include="Clock.fs" />
    <Compile Include="Types.fs" />
    <Compile Include="Components.fs" />
    <Compile Include="App.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Shared.fsproj" />
  </ItemGroup>
  <Import Project="..\..\..\.paket\Paket.Restore.targets" />
</Project>
```

**Comment by alfonsogarciacaro** [comment]
Thansk @OnurGumus. Hmm, it doesn't look particularly difficult to parse, although I'm not sure if we've already tried Buildalyzer in a project using Paket. Not sure if it will fix the issue but I tried something in the latest release. Could you please update to theta-014 and let me know if it works for you?

**Comment by OnurGumus** [comment]
Hi, theta-014 works fine, thanks.
