### ISSUE TITLE
Fable 4 regression: using C#-style optional parameters crashes compilation

### ISSUE THREAD

**Issue by jwosty** [fable-compiler/Fable#3326]
### Description

Looks like Fable 4 doesn't like it when you instantiate an Attribute with `null` as a parameter. It works in Fable 3.

### Repro code

Add the following code anywhere into a Fable project:

```fsharp
open System.Runtime.InteropServices
type Foo() =
    member this.Return ([<Optional; DefaultParameterValue(null:obj)>] x: obj) = x
let x = Foo()
let y = x.Return ()
// note that replacing the previous line with this next line still crashes Fable:
// let y = x.Return 42
```

### Expected and actual results

Expected: The code compiles and runs, and `y` has the value `null`.

Actual: Fable crashes:

```
./Program.fs(1,1): error EXCEPTION: Object reference not set to an instance of an object.
   at Fable.Transforms.AST.makeConstFromObj(Object value) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\Transforms.Util.fs:line 569
   at <StartupCode$Fable-Transforms>.$FSharp2Fable.Util.-ctor@173-1.Invoke(Tuple`2 tupledArg) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\FSharp2Fable.Util.fs:line 173
   at Microsoft.FSharp.Core.OptionModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpOption`1 option) in /home/dev/Projects/fsharp/src/FSharp.Core/option.fs:line 98
   at Fable.Transforms.FSharp2Fable.FsParam..ctor(FSharpParameter p, FSharpOption`1 isNamed) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\FSharp2Fable.Util.fs:line 166
   at <StartupCode$Fable-Transforms>.$FSharp2Fable.Util.Fable-AST-Fable-MemberFunctionOrValue-get_CurriedParameterGroups@222.Invoke(FSharpParameter p) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\FSharp2Fable.Util.fs:line 228
   at Fable.Seq.mapToList@47.Invoke(FSharpList`1 li, a x) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\Global\Prelude.fs:line 47
   at Microsoft.FSharp.Collections.SeqModule.Fold[T,TState](FSharpFunc`2 folder, TState state, IEnumerable`1 source) in /home/dev/Projects/fsharp/src/FSharp.Core/seq.fs:line 883
   at Fable.Seq.mapToList[a,b](FSharpFunc`2 f, IEnumerable`1 xs) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\Global\Prelude.fs:line 47
   at <StartupCode$Fable-Transforms>.$FSharp2Fable.Util.Fable-AST-Fable-MemberFunctionOrValue-get_CurriedParameterGroups@222-1.Invoke(IList`1 xs)
   at Fable.Seq.mapToList@47.Invoke(FSharpList`1 li, a x) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\Global\Prelude.fs:line 47
   at Microsoft.FSharp.Collections.SeqModule.Fold[T,TState](FSharpFunc`2 folder, TState state, IEnumerable`1 source) in /home/dev/Projects/fsharp/src/FSharp.Core/seq.fs:line 883
   at Fable.Seq.mapToList[a,b](FSharpFunc`2 f, IEnumerable`1 xs) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\Global\Prelude.fs:line 47
   at Fable.Transforms.FSharp2Fable.FsMemberFunctionOrValue.Fable.AST.Fable.MemberFunctionOrValue.get_CurriedParameterGroups() in C:\Users\alfon\repos\Fable\src\Fable.Transforms\FSharp2Fable.Util.fs:line 221
   at Fable.Transforms.AST.getParamsInfo(MemberFunctionOrValue memberInfo) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\Transforms.Util.fs:line 722
   at Fable.Transforms.Fable2Babel.Util.transformCallArgs(IBabelCompiler com, Context ctx, ArgsInfo info) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\Fable2Babel.fs:line 1239
   at Fable.Transforms.Fable2Babel.Util.transformCall(IBabelCompiler com, Context ctx, FSharpOption`1 range, Type typ, Expr callee, CallInfo callInfo) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\Fable2Babel.fs:line 1411
   at Fable.Transforms.Fable2Babel.Util.transformBindingExprBody(IBabelCompiler com, Context ctx, Ident var, Expr value) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\Fable2Babel.fs:line 1546
   at Fable.Transforms.Fable2Babel.Util.transformBindingAsStatements(IBabelCompiler com, Context ctx, Ident var, Expr value) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\Fable2Babel.fs:line 1559
   at Fable.Transforms.Fable2Babel.Util.transformAsStatements(IBabelCompiler com, Context ctx, FSharpOption`1 returnStrategy, Expr expr) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\Fable2Babel.fs:line 1967
   at Fable.Transforms.Fable2Babel.Util.transformFunction(IBabelCompiler com, Context ctx, FSharpOption`1 name, FSharpList`1 args, Expr body) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\Fable2Babel.fs:line 2040
   at Fable.Transforms.Fable2Babel.Compiler.BabelCompiler.Fable.Transforms.Fable2Babel.IBabelCompiler.TransformFunction(Context ctx, FSharpOption`1 name, FSharpList`1 args, Expr body) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\Fable2Babel.fs:line 2575
   at Fable.Transforms.Fable2Babel.Annotation.transformFunctionWithAnnotations(IBabelCompiler com, Context ctx, FSharpOption`1 name, FSharpOption`1 typeParams, FSharpList`1 args, Expr body) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\Fable2Babel.fs:line 614
   at Fable.Transforms.Fable2Babel.Util.getMemberArgsAndBody(IBabelCompiler com, Context ctx, MemberKind kind, MemberFunctionOrValue info, FSharpList`1 args, Expr body) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\Fable2Babel.fs:line 928
   at Fable.Transforms.Fable2Babel.Util.transformModuleFunction(IBabelCompiler com, Context ctx, MemberFunctionOrValue info, String membName, FSharpList`1 args, Expr body) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\Fable2Babel.fs:line 2204
   at Fable.Transforms.Fable2Babel.Util.transformDeclaration@2404-2.Invoke(Context ctx) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\Fable2Babel.fs:line 2426
   at Fable.Transforms.Fable2Babel.Util.withCurrentScope@2390-1.Invoke(FSharpFunc`2 f) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\Fable2Babel.fs:line 2391
   at Microsoft.FSharp.Primitives.Basics.List.collectToFreshConsTail[T,TResult](FSharpFunc`2 f, FSharpList`1 list, FSharpList`1 cons) in /home/dev/Projects/fsharp/src/FSharp.Core/local.fs:line 434
   at Microsoft.FSharp.Primitives.Basics.List.collect[T,TResult](FSharpFunc`2 f, FSharpList`1 list) in /home/dev/Projects/fsharp/src/FSharp.Core/local.fs:line 442
   at Fable.Transforms.Fable2Babel.Compiler.transformFile(Compiler com, File file) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\Fable2Babel.fs:line 2618
   at Fable.Cli.Pipeline.Js.compileFile@121.Invoke(Unit unitVar) in C:\Users\alfon\repos\Fable\src\Fable.Cli\Pipeline.fs:line 122
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in /home/dev/Projects/fsharp/src/FSharp.Core/async.fs:line 510
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in /home/dev/Projects/fsharp/src/FSharp.Core/async.fs:line 112
Compilation failed
``` 

Stacktrace indicates the crash is coming from here: https://github.com/fable-compiler/Fable/blob/4.0.0-theta-018/src/Fable.Transforms/Transforms.Util.fs#L569 . I'm betting that `makeConstFromObj` just needs to have a case for `null` values.

### Related information

* Fable version: 4.0.0-theta-018
* Operating system: macOS 12.6

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for reporting and sorry for the late reply! Should be fixed in the next release.
