### ISSUE TITLE
Fable 4.0.2 breaks Fable.Lit

### ISSUE THREAD

**Issue by OnurGumus** [fable-compiler/Fable#3389]
### Description

I don't have an isolated case unfortunately, but most definitely updating Fable causes Fable.Lit fail with below error. Not sure what is the reason. Reverting to Fable 4.0.1 from tools solves the problem.

```
lit-html.ts:842 
        
Uncaught (in promise) Error: Internal Error: expected template strings to be an array
with a 'raw' field. Faking a template strings array by
calling html or svg like an ordinary function is effectively
the same as calling unsafeHtml and can lead to major security
issues, e.g. opening your code up to XSS attacks.

If you're using the html or svg tagged template functions normally
and still seeing this error, please file a bug at
https://github.com/lit/lit/issues/new?template=bug_report.md
and include information about your build tooling, if any.
    at getTemplateHtml (lit-html.ts:842:11)
    at new Template (lit-html.ts:873:31)
    at ChildPart._$getTemplate (lit-html.ts:1561:53)
    at ChildPart._commitTemplateResult (lit-html.ts:1514:16)
    at ChildPart._$setValue (lit-html.ts:1375:12)
    at render (lit-html.ts:2172:8)
    at classExpr.update (lit-element.ts:165:24)
    at classExpr.performUpdate (reactive-element.ts:1331:14)
    at classExpr.scheduleUpdate (reactive-element.ts:1263:17)
    at classExpr.__enqueueUpdate (reactive-element.ts:1235:25)

**Comment by alfonsogarciacaro** [comment]
Should be fixed in 4.0.2. Please reopen if you still have problems. Interestingly, I couldn't reproduce the error message but lit behave indeed "funny" with Fable 4.0.1.
