### ISSUE TITLE
Difficult to reproduce Fable build errors

### ISSUE THREAD

**Issue by cloudRoutine** [fable-compiler/Fable#346]
For the past few days I've been trying to track down the source of a fable build error when building the [ionide vscode fsharp extension](https://github.com/ionide/ionide-vscode-fsharp)

I can build the extension without issue off of a fresh clone of the the repository on my Windows 10 machine and my Ubuntu VM, but @onionhammer hasn't been able to successfully compile with Fable on his Windows 10 machine or his Windows 10 VM.
(my installations use a locally installed fable-compiler via the extension's `devDependencies`)

It's failing with the output
```
> fable ../src/Ionide.FSharp.fsproj -s -o ../release -m commonjs --verbose
Fable F# to JS compiler version 0.5.2
PROJECT FILE: c:\Users\Erik\ionide-vscode-fsharp\src\Ionide.FSharp.fsproj
OUTPUT DIR: c:\Users\Erik\ionide-vscode-fsharp\release
WORKING DIR: c:\Users\Erik\ionide-vscode-fsharp\src
FABLE COMMAND: cmd /S /C "C:\Users\Erik\AppData\Roaming\npm\node_modules\fable-compiler\bin\Fable.Client.Node.exe --projFile Ionide.FSharp.fsproj --copyExt true"
Start compilation...
ERROR: Build was not evaluated, expected the results to be ready after 'Eval'.
   at Microsoft.FSharp.Compiler.IncrementalBuilder.GetCheckResultsAndImplementationsForProject()
   at Microsoft.FSharp.Compiler.SourceCodeServices.BackgroundCompiler.ParseAndCheckProjectImpl(FSharpProjectOptions options)
   at <StartupCode$FSharp-Compiler-Service>.$Service.ParseAndCheckProject@2520.Invoke(CancellationToken _ct)
   at <StartupCode$FSharp-Compiler-Service>.$Reactor.EnqueueAndAwaitOpAsync@139-2.Invoke(Unit unitVar0)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](Result`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at Fable.Client.Node.Main.parseFSharpProject(ICompiler com, FSharpChecker checker, FSharpProjectOptions projOptions)
   at Fable.Client.Node.Main.compile(ICompiler com, FSharpChecker checker, FSProjectInfo projInfo)
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "c:\\Users\\Erik\\ionide-vscode-fsharp\\packages\\Node.js\\node.exe" "c:\\Users\\Erik\\ionide-vscode-fsharp\\packages\\Npm.js\\tools\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v5.3.0
npm ERR! npm  v2.13.1
npm ERR! code ELIFECYCLE
npm ERR! Ionide-fsharp@2.2.12 build: `fable ../src/Ionide.FSharp.fsproj -s -o ../release -m commonjs --verbose`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Ionide-fsharp@2.2.12 build script 'fable ../src/Ionide.FSharp.fsproj -s -o ../release -m commonjs --verbose'.
npm ERR! This is most likely a problem with the Ionide-fsharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     fable ../src/Ionide.FSharp.fsproj -s -o ../release -m commonjs --verbose
npm ERR! You can get their info via:
npm ERR!     npm owner ls Ionide-fsharp
npm ERR! There is likely additional logging output above.
```
^ this is using the local npm and node.js that are installed via paket as a dependency of the repository

I've also tried using the globally installed npm and node.js by running 
```
ionide-vscode-fsharp\release> npm run-script build --loglevel silly
```
which still fails and produces the debug log output
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run-script',
1 verbose cli   'build',
1 verbose cli   '--loglevel',
1 verbose cli   'silly' ]
2 info using npm@3.10.3
3 info using node@v6.3.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle Ionide-fsharp@2.2.12~prebuild: Ionide-fsharp@2.2.12
6 silly lifecycle Ionide-fsharp@2.2.12~prebuild: no script for prebuild, continuing
7 info lifecycle Ionide-fsharp@2.2.12~build: Ionide-fsharp@2.2.12
8 verbose lifecycle Ionide-fsharp@2.2.12~build: unsafe-perm in lifecycle true
9 verbose lifecycle Ionide-fsharp@2.2.12~build: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Erik\ionide-vscode-fsharp\release\node_modules\.bin;C:\Program Files\nodejs;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\Erik\AppData\Roaming\npm
10 verbose lifecycle Ionide-fsharp@2.2.12~build: CWD: C:\Users\Erik\ionide-vscode-fsharp\release
11 silly lifecycle Ionide-fsharp@2.2.12~build: Args: [ '/d /s /c',
11 silly lifecycle   'fable ../src/Ionide.FSharp.fsproj -s -o ../release -m commonjs --verbose' ]
12 silly lifecycle Ionide-fsharp@2.2.12~build: Returned: code: 1  signal: null
13 info lifecycle Ionide-fsharp@2.2.12~build: Failed to exec build script
14 verbose stack Error: Ionide-fsharp@2.2.12 build: `fable ../src/Ionide.FSharp.fsproj -s -o ../release -m commonjs --verbose`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid Ionide-fsharp@2.2.12
16 verbose cwd C:\Users\Erik\ionide-vscode-fsharp\release
17 error Windows_NT 10.0.10240
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "build" "--loglevel" "silly"
19 error node v6.3.1
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error Ionide-fsharp@2.2.12 build: `fable ../src/Ionide.FSharp.fsproj -s -o ../release -m commonjs --verbose`
22 error Exit status 1
23 error Failed at the Ionide-fsharp@2.2.12 build script 'fable ../src/Ionide.FSharp.fsproj -s -o ../release -m commonjs --verbose'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the Ionide-fsharp package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     fable ../src/Ionide.FSharp.fsproj -s -o ../release -m commonjs --verbose
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs Ionide-fsharp
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls Ionide-fsharp
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

@onionhammer was able to successfully compile the project using a globally installed fable
```
ionide-vscode-fsharp> fable fable-load.fsx -m commonjs --verbose
```
where the contents of `fable-load.fsx` is
```fsharp
#I __SOURCE_DIRECTORY__
#r "release/node_modules/fable-core/Fable.Core.dll"
#load "paket-files/Ionide/ionide-vscode-helpers/Fable.Import.VSCode.fs"
      "paket-files/Ionide/ionide-vscode-helpers/Helpers.fs"
      "paket-files/Ionide/ionide-vscode-helpers/Fable.Import.Axios.fs"
      "src/Core/DTO.fs"
      "src/Core/LanguageService.fs"
      "src/Core/Project.fs"
      "src/Components/Linter.fs"
      "src/Components/Tooltip.fs"
      "src/Components/Autocomplete.fs"
      "src/Components/ParameterHints.fs"
      "src/Components/Definition.fs"
      "src/Components/References.fs"
      "src/Components/Highlights.fs"
      "src/Components/Symbols.fs"
      "src/Components/Rename.fs"
      "src/Components/WorkspaceSymbols.fs"
      "src/Components/Environment.fs"
      "src/Components/Fsi.fs"
      "src/Components/QuickInfo.fs"
      "src/Components/WebPreview.fs"
      "src/Components/Forge.fs"
      "src/fsharp.fs"
```
On the failing VM:
* F# 4.0 was installed
* F# installation was added to path 
* build tools 2013 (msbuild 12) installed
* build tools 2015 (msbuild 14) installed 
* windows 10 sdk installed
* node.js 6.3.1 installed
* fable 0.5.2 installed globally (and locally for compiling from within vscode/via the FAKE build script)
* Microsoft .NET Framework 4.6.2 SDK

**Comment by alfonsogarciacaro** [comment]
I'm also very puzzled by these errors on some machines. The only issue where I've seen `Build was not evaluated, expected the results to be ready after 'Eval'.` is #92, but it seems to be a different problem (apparently it was solved by changing some `Import` targets in the `fsproj` file).

Fable is shipping without the `pdb` files of FCS and Project Cracker, I wonder if including them could give more information about the error.

**Comment by cloudRoutine** [comment]
I read through that issue and @onionhammer tried changing the import targets the same way but that didn't work either

**Comment by alfonsogarciacaro** [comment]
Hopefully build issues should be fixed now and Fable also gives more info (see #345) so I'm closing this for now. Let's open it again if MSBuild strikes back

**Comment by smoothdeveloper** [comment]
I'm getting this issue on a clean windows 7 install trying to build https://github.com/ionide/ionide-vscode-fsharp

```
Starting Target: RunScript (==> Clean, Clean)
C:\dev\ionide-vscode-fsharp\packages\Npm.js\tools\npm.cmd install
C:\dev\ionide-vscode-fsharp\packages\Npm.js\tools\npm.cmd run build

> Ionide-fsharp@2.20.0 prebuild C:\dev\ionide-vscode-fsharp\release
> npm update


> Ionide-fsharp@2.20.0 build C:\dev\ionide-vscode-fsharp\release
> fable ../src/Ionide.FSharp.fsproj -s -o ../release -m commonjs --verbose

Fable F# to JS compiler version 0.6.15

PROJECT FILE: C:\dev\ionide-vscode-fsharp\src\Ionide.FSharp.fsproj
OUTPUT DIR: C:\dev\ionide-vscode-fsharp\release
WORKING DIR: C:\dev\ionide-vscode-fsharp\src

FABLE COMMAND: cmd /S /C "C:\dev\ionide-vscode-fsharp\release\node_modules\fable
-compiler\bin\Fable.Client.Node.exe --projFile Ionide.FSharp.fsproj --copyExt tr
ue"

fable-compiler 0.6.15: Start compilation...

F# COMPILER OPTIONS:
--define:FABLE_COMPILER

ERROR: Build was not evaluated, expected the results to be ready after 'Eval'.
   at Microsoft.FSharp.Compiler.IncrementalBuilder.GetCheckResultsAndImplementat
ionsForProject()
   at Microsoft.FSharp.Compiler.SourceCodeServices.BackgroundCompiler.ParseAndCh
eckProjectImpl(FSharpProjectOptions options)
   at <StartupCode$FSharp-Compiler-Service>.$Service.ParseAndCheckProject@2520.I
nvoke(CancellationToken _ct)
   at <StartupCode$FSharp-Compiler-Service>.$Reactor.EnqueueAndAwaitOpAsync@139-
2.Invoke(Unit unitVar0)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](Result`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](Cancella
tionToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 com
putation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at Fable.Client.Node.Main.parseFSharpProject(ICompiler com, FSharpChecker che
cker, FSharpProjectOptions projOptions)
   at Fable.Client.Node.Main.compile(ICompiler com, FSharpChecker checker, FSPro
jectInfo projInfo)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\dev\\ionide-vscode-fsharp\\packages\\Node.js\\node.exe" "C:\\
dev\\ionide-vscode-fsharp\\packages\\Npm.js\\tools\\node_modules\\npm\\bin\\npm-
cli.js" "run" "build"
npm ERR! node v5.3.0
npm ERR! npm  v2.13.1
npm ERR! code ELIFECYCLE
npm ERR! Ionide-fsharp@2.20.0 build: `fable ../src/Ionide.FSharp.fsproj -s -o ..
/release -m commonjs --verbose`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Ionide-fsharp@2.20.0 build script 'fable ../src/Ionide.FS
harp.fsproj -s -o ../release -m commonjs --verbose'.
npm ERR! This is most likely a problem with the Ionide-fsharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     fable ../src/Ionide.FSharp.fsproj -s -o ../release -m commonjs --ve
rbose
npm ERR! You can get their info via:
npm ERR!     npm owner ls Ionide-fsharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\dev\ionide-vscode-fsharp\release\npm-debug.log
Running build failed.
Error:
System.Exception: Error while running 'C:\dev\ionide-vscode-fsharp\packages\Npm.
js\tools\npm.cmd' with args: run build
   at FSI_0005.Build.run@49-3.Invoke(String message) in C:\dev\ionide-vscode-fsh
arp\build.fsx:line 49
   at FSI_0005.Build.run(String cmd, String args, String dir) in C:\dev\ionide-v
scode-fsharp\build.fsx:line 49
   at FSI_0005.Build.clo@80-1.Invoke(Unit _arg2) in C:\dev\ionide-vscode-fsharp\
build.fsx:line 81
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake
\src\app\FakeLib\TargetHelper.fs:line 492

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target     Duration
------     --------
Clean      00:00:00.0337613
Total:     00:00:28.6392802
Status:    Failure
---------------------------------------------------------------------
  1) System.Exception: Error while running 'C:\dev\ionide-vscode-fsharp\packages
\Npm.js\tools\npm.cmd' with args: run build
   at FSI_0005.Build.run@49-3.Invoke(String message) in C:\dev\ionide-vscode-fsh
arp\build.fsx:line 49
   at FSI_0005.Build.run(String cmd, String args, String dir) in C:\dev\ionide-v
scode-fsharp\build.fsx:line 49
   at FSI_0005.Build.clo@80-1.Invoke(Unit _arg2) in C:\dev\ionide-vscode-fsharp\
build.fsx:line 81
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake
\src\app\FakeLib\TargetHelper.fs:line 492
---------------------------------------------------------------------

C:\dev\ionide-vscode-fsharp>
```

I have F# 4.0, MSBuild tools 2013 & 2015, installed nodejs 7.4.0 and npm 4.1.1

Please let me know if there is anything you'd like me to try to help figure out this issue.

**Comment by alfonsogarciacaro** [comment]
Sorry, that's Fable 0.6.x, I cannot provide support for that... mainly because I don't remember anything :/

**Comment by smoothdeveloper** [comment]
@alfonsogarciacaro thanks, @Krzysztof-Cieslak do you have a chance to upgrade to a better Fable in ionide projects?
