### ISSUE TITLE
Cannot infer key and value of ClassName

### ISSUE THREAD

**Issue by nojaf** [fable-compiler/Fable#3488]
### Description

Hello,

I'm encountering a strange bug at runtime with an `if/then/else` inside a `React` `Prop`:

```fsharp
div [ ClassName(if true then "show" else "") ] []
```
leads to
```
Error: Cannot infer key and value of ClassName show
    at u (MapUtil.js:34:15)
    at U (MapUtil.js:71:13)
    at App (Library.js:14:39)
    at $i (react-dom.production.min.js:167:137)
    at da (react-dom.production.min.js:290:337)
    at aa (react-dom.production.min.js:280:389)
    at vf (react-dom.production.min.js:280:320)
    at jr (react-dom.production.min.js:280:180)
    at mo (react-dom.production.min.js:273:245)
    at on (react-dom.production.min.js:127:105)
```

### Repro code

https://github.com/nojaf/fable-prop-bug

### Expected and actual results

The code works when `ClassName h1Class` is a separate value but fails when it is inline like `ClassName(if true then "show" else "")`.

### Related information

* Fable version: `4.1.4`
* Operating system: Windows

**Comment by robitar** [comment]
Out of curiosity, what happens if you add a space after the `ClassName`:

```f#
div [ ClassName (if true then "show" else "") ] []
```

**Comment by nojaf** [comment]
Nothing changes.

**Comment by robitar** [comment]
Ah I see, just a random thought. I suppose your workaround is to pull the expression into a local and use that.. strange though.

**Comment by MangelMaxime** [comment]
Can't reproduce after updating all the dependencies and using Fable 5 RC in the reproduction repository.

So we probably fixed it without knowing
