### ISSUE TITLE
[Python] Equality of record with optional filed doesn't works if the field are set to `None`

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#3605]
### Description

```fs
open Fable.Core.Testing

type SmallRecord2 =
    { optionalField : string option }

let a = Ok({ optionalField = None })
let b = Ok({ optionalField = None })

// printfn "%A" (a = b) This version of the equality crash too
printfn "%A" (Assert.AreEqual(a, b, ""))
```

Error:

```
Watching ../..
Traceback (most recent call last):
  File "/Users/mmangel/Workspaces/Github/thoth-org/Thoth.Json/tests/Thoth.Json.Tests.Python/./fableBuild/./Main.py", line 118, in <module>
    main(sys.argv[1:])
  File "/Users/mmangel/Workspaces/Github/thoth-org/Thoth.Json/tests/Thoth.Json.Tests.Python/./fableBuild/./Main.py", line 112, in main
    arg: None = assert_equal(a, b, "")
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mmangel/Workspaces/Github/thoth-org/Thoth.Json/tests/Thoth.Json.Tests.Python/fableBuild/fable_modules/fable_library/util.py", line 352, in assert_equal
    if not equals(actual, expected):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mmangel/Workspaces/Github/thoth-org/Thoth.Json/tests/Thoth.Json.Tests.Python/fableBuild/fable_modules/fable_library/util.py", line 226, in equals
    return a == b
           ^^^^^^
  File "/Users/mmangel/Workspaces/Github/thoth-org/Thoth.Json/tests/Thoth.Json.Tests.Python/fableBuild/fable_modules/fable_library/types.py", line 99, in __eq__
    return self.fields == other.fields
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mmangel/Workspaces/Github/thoth-org/Thoth.Json/tests/Thoth.Json.Tests.Python/fableBuild/fable_modules/fable_library/types.py", line 185, in __eq__
    return self.Equals(other)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/mmangel/Workspaces/Github/thoth-org/Thoth.Json/tests/Thoth.Json.Tests.Python/fableBuild/fable_modules/fable_library/types.py", line 170, in Equals
    return record_equals(self, other)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mmangel/Workspaces/Github/thoth-org/Thoth.Json/tests/Thoth.Json.Tests.Python/fableBuild/fable_modules/fable_library/types.py", line 146, in record_equals
    return record_compare_to(self, other) == 0
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mmangel/Workspaces/Github/thoth-org/Thoth.Json/tests/Thoth.Json.Tests.Python/fableBuild/fable_modules/fable_library/types.py", line 123, in record_compare_to
    if self.__dict__[name] < other.__dict__.get(name):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
```

### Expected and actual results

Equality test should not crash

### Related information

* Fable version: `3.5.0`
* Operating system: OSX

**Comment by MangelMaxime** [comment]
A similar problem occurs when running the following:

```fs
let a = Ok({ optionalField = None })
    let b = Ok({ optionalField = Some "" })

    // printfn "%A" (a = b)
    printfn "%A" (Assert.AreEqual(a, b, ""))
```
