### ISSUE TITLE
`--test:MSBuildCracker` not working against Glutinum project

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#3776]
### Description

Hello @nojaf,

I tried using `dotnet fable --test:MSBuildCracker` against Glutinum projects but I am getting an error:

> Duplicate 'PackageReference' items found. Remove the duplicate items or use the Update functionality to ensure a consistent restore behavior. The duplicate 'PackageReference' items are: FSharp.Core , FSharp.Core 8.0.100; Fable.Core 4.2, Fable.Core ; Fable.Node 1.2, Fable.Node ; Glutinum.Chalk 1.0, Glutinum.Chalk ./Users/mmangel/Workspaces/Github/glutinum-org/Glutinum.Converter/src/Glutinum.Converter/Glutinum.Converter.fsproj : error NU1008: Projects that use central package version management should not define the version on the PackageReference items but on the PackageVersion items: Fable.Core;Fable.Node;Glutinum.Chalk.Build failed. Properties, Items, and Target results cannot be obtained. See details in stderr above.
)

Full error message:

```text
dotnet fable --test:MSBuildCracker --noCache
Fable 4.14.0: F# to JavaScript compiler
Minimum @fable-org/fable-library-js version (when installed from npm): 1.2.0

Thanks to the contributor! @enricosada
Stand with Ukraine! https://standwithukraine.com.ua/

Parsing Glutinum.Converter.fsproj...
Unhandled exception. System.AggregateException: One or more errors occurred. (In /Users/mmangel/.nuget/packages/fable/4.14.0/tools/net6.0/any:
dotnet msbuild /Users/mmangel/Workspaces/Github/glutinum-org/Glutinum.Converter/src/Glutinum.Converter/Glutinum.Converter.fsproj /restore /t:ResolveAssemblyReferencesDesignTime,ResolveProjectReferencesDesignTime,ResolvePackageDependenciesDesignTime,FindReferenceAssembliesForReferences,_GenerateCompileDependencyCache,_ComputeNonExistentFileProperty,BeforeBuild,BeforeCompile,CoreCompile /p:Fable=True /p:Configuration=Release /p:TargetFramework=netstandard2.0 /p:DesignTimeBuild=True /p:SkipCompilerExecution=True /p:ProvideCommandLineArgs=True /p:RestoreUseStaticGraphEvaluation=False /p:RestoreLockedMode=false /p:RestorePackagesWithLockFile=false  /p:NuGetLockFilePath=Fable.lock /p:NonExistentFile="__NonExistentSubDir__/__NonExistentFile__" --getItem:FscCommandLineArgs --getItem:ProjectReference --getProperty:OutputType -warnAsMessage:NU1608
failed with
/Users/mmangel/Workspaces/Github/glutinum-org/Glutinum.Converter/src/Glutinum.Converter/Glutinum.Converter.fsproj : warning NU1504: Duplicate 'PackageReference' items found. Remove the duplicate items or use the Update functionality to ensure a consistent restore behavior. The duplicate 'PackageReference' items are: FSharp.Core , FSharp.Core 8.0.100; Fable.Core 4.2, Fable.Core ; Fable.Node 1.2, Fable.Node ; Glutinum.Chalk 1.0, Glutinum.Chalk ./Users/mmangel/Workspaces/Github/glutinum-org/Glutinum.Converter/src/Glutinum.Converter/Glutinum.Converter.fsproj : error NU1008: Projects that use central package version management should not define the version on the PackageReference items but on the PackageVersion items: Fable.Core;Fable.Node;Glutinum.Chalk.Build failed. Properties, Items, and Target results cannot be obtained. See details in stderr above.
)
 ---> System.Exception: In /Users/mmangel/.nuget/packages/fable/4.14.0/tools/net6.0/any:
dotnet msbuild /Users/mmangel/Workspaces/Github/glutinum-org/Glutinum.Converter/src/Glutinum.Converter/Glutinum.Converter.fsproj /restore /t:ResolveAssemblyReferencesDesignTime,ResolveProjectReferencesDesignTime,ResolvePackageDependenciesDesignTime,FindReferenceAssembliesForReferences,_GenerateCompileDependencyCache,_ComputeNonExistentFileProperty,BeforeBuild,BeforeCompile,CoreCompile /p:Fable=True /p:Configuration=Release /p:TargetFramework=netstandard2.0 /p:DesignTimeBuild=True /p:SkipCompilerExecution=True /p:ProvideCommandLineArgs=True /p:RestoreUseStaticGraphEvaluation=False /p:RestoreLockedMode=false /p:RestorePackagesWithLockFile=false  /p:NuGetLockFilePath=Fable.lock /p:NonExistentFile="__NonExistentSubDir__/__NonExistentFile__" --getItem:FscCommandLineArgs --getItem:ProjectReference --getProperty:OutputType -warnAsMessage:NU1608
failed with
/Users/mmangel/Workspaces/Github/glutinum-org/Glutinum.Converter/src/Glutinum.Converter/Glutinum.Converter.fsproj : warning NU1504: Duplicate 'PackageReference' items found. Remove the duplicate items or use the Update functionality to ensure a consistent restore behavior. The duplicate 'PackageReference' items are: FSharp.Core , FSharp.Core 8.0.100; Fable.Core 4.2, Fable.Core ; Fable.Node 1.2, Fable.Node ; Glutinum.Chalk 1.0, Glutinum.Chalk ./Users/mmangel/Workspaces/Github/glutinum-org/Glutinum.Converter/src/Glutinum.Converter/Glutinum.Converter.fsproj : error NU1008: Projects that use central package version management should not define the version on the PackageReference items but on the PackageVersion items: Fable.Core;Fable.Node;Glutinum.Chalk.Build failed. Properties, Items, and Target results cannot be obtained. See details in stderr above.

   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1448.Invoke(String message)
   at Microsoft.FSharp.Core.PrintfModule.gprintf[a,TState,TResidue,TResult,TPrinter](FSharpFunc`2 envf, PrintfFormat`4 format) in /home/dev/Projects/fsharp/src/FSharp.Core/printf.fs:line 1398
   at Fable.Compiler.MSBuildCrackerResolverModule.dotnet_msbuild_with_defines@32.MoveNext() in /workspaces/Fable/src/Fable.Compiler/MSBuildCrackerResolver.fs:line 58
   --- End of inner exception stack trace ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in /home/dev/Projects/fsharp/src/FSharp.Core/async.fs:line 454
   at Microsoft.FSharp.Control.AsyncPrimitives.RunImmediate[a](CancellationToken cancellationToken, FSharpAsync`1 computation) in /home/dev/Projects/fsharp/src/FSharp.Core/async.fs:line 1159
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in /home/dev/Projects/fsharp/src/FSharp.Core/async.fs:line 1165
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in /home/dev/Projects/fsharp/src/FSharp.Core/async.fs:line 1515
   at Fable.Compiler.ProjectCracker.crackMainProject(ProjectCrackerResolver resolver, CrackerOptions opts) in /workspaces/Fable/src/Fable.Compiler/ProjectCracker.fs:line 540
   at Fable.Compiler.ProjectCracker.getCrackedProjectsFromMainFsproj(ProjectCrackerResolver resolver, CrackerOptions opts) in /workspaces/Fable/src/Fable.Compiler/ProjectCracker.fs:line 576
   at Fable.Compiler.ProjectCracker.getCrackedProjects(ProjectCrackerResolver resolver, CrackerOptions opts) in /workspaces/Fable/src/Fable.Compiler/ProjectCracker.fs:line 596
   at Fable.Compiler.ProjectCracker.retry@606(ProjectCrackerResolver resolver, CrackerOptions opts, DateTime retryUntil, Unit unitVar0) in /workspaces/Fable/src/Fable.Compiler/ProjectCracker.fs:line 608
   at Fable.Compiler.ProjectCracker.retryGetCrackedProjects(ProjectCrackerResolver resolver, CrackerOptions opts) in /workspaces/Fable/src/Fable.Compiler/ProjectCracker.fs:line 618
   at Fable.Compiler.ProjectCracker.getFullProjectOpts(ProjectCrackerResolver resolver, CrackerOptions opts) in /workspaces/Fable/src/Fable.Compiler/ProjectCracker.fs:line 915
   at Fable.Compiler.Util.Performance.measure[a](FSharpFunc`2 f) in /workspaces/Fable/src/Fable.Compiler/Util.fs:line 834
   at Fable.Cli.Main.ProjectCracked.Init(CliArgs cliArgs, Boolean useMSBuildForCracking, FSharpOption`1 evaluateOnly) in /workspaces/Fable/src/Fable.Cli/Main.fs:line 373
   at Fable.Cli.Main.compilationCycle@998.Invoke(Unit unitVar) in /workspaces/Fable/src/Fable.Cli/Main.fs:line 1003
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in /home/dev/Projects/fsharp/src/FSharp.Core/async.fs:line 510
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in /home/dev/Projects/fsharp/src/FSharp.Core/async.fs:line 112
--- End of stack trace from previous location ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in /home/dev/Projects/fsharp/src/FSharp.Core/async.fs:line 454
   at Microsoft.FSharp.Control.AsyncPrimitives.QueueAsyncAndWaitForResultSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout) in /home/dev/Projects/fsharp/src/FSharp.Core/async.fs:line 1139
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in /home/dev/Projects/fsharp/src/FSharp.Core/async.fs:line 1166
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in /home/dev/Projects/fsharp/src/FSharp.Core/async.fs:line 1515
   at Fable.Cli.Entry.Run@298-3.Invoke(Unit _arg5) in /workspaces/Fable/src/Fable.Cli/Entry.fs:line 392
   at Fable.Cli.Entry.main@518-1.Invoke(Tuple`2 _arg2) in /workspaces/Fable/src/Fable.Cli/Entry.fs:line 524
   at Fable.Cli.Entry.main(String[] argv) in /workspaces/Fable/src/Fable.Cli/Entry.fs:line 516
```

I have the same issues with another project of mine that I can't share (private source). 

At first, I tough the problem was because I am using central package management from NuGet but after trying severals times to make a small reproduction project it seems to not be the case...

I will continue to try identify the problem but if you have time could you please have a look? Perhaps, you will be able to spot something that I am missing.

To reproduce the error:

1. Clone https://github.com/glutinum-org/cli
2. `dotnet tool restore`
3. `cd src/Glutinum.Converter`
4. `dotnet fable --test:MSBuildCracker --noCache`
5. The previous command should fail

### Repro code

Please provide the F# code to reproduce the problem or a link to the [REPL](https://fable.io/repl/).
Ideally, it should be possible to easily turn this code into a unit test.

### Expected and actual results

Please provide the expected and actual results.

### Related information

* Fable version: `4.14.0`
* Operating system: OSX

**Comment by nojaf** [comment]
Hi,

Seems to work in Windows for me:

![image](https://github.com/fable-compiler/Fable/assets/2621499/05962475-7448-463d-b926-44a208d8212b)

What SDK version are you using? I have `8.0.201`

**Comment by nojaf** [comment]
Could you also remove your `obj` and try again?

**Comment by goswinr** [comment]
What if you remove all explicit refrences to Fsharp core ?
https://github.com/glutinum-org/cli/blob/663dd7134ca411b22809d15f6fcb7cb407676f7f/src/Glutinum.Build/Glutinum.Build.fsproj#L22

**Comment by MangelMaxime** [comment]
@goswinr When using `CentralPackageManagement` you can't use the implicit version of FSharp.Core because it comes as `<PackageReference Update="FSharp.Core" Version="4.7.2" />` with a version attached to it.

But when using `CentralPackageManagement` your `PackageReference` can't have the `Version` has it is provided by `<PackageVersion Include="FSharp.Core" Version="8.0.101" />` in the `Directory.Packages.props` file.

> Could you also remove your `obj` and try again?

It was indeed the solution ... I should have known that as this is often the solution with .NET 🤦‍♂️

Thank you for saving my sanity 🤣
