### ISSUE TITLE
0.7.0 reference type issue

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#521]
Compiling this code with latest 0.7.0 fails:
```
type TestRef = TestRef of bool ref
```
and produces this error:
```
{"type":"ERROR",
 "message":"Cannot access type: Microsoft.FSharp.Core.FSharpRef",
 "stack":"
   at Fable.Fable2Babel.Util.typeRef@147.Invoke(String message)
   at Fable.Fable2Babel.Util.prepareArgs@77.Invoke(Expr _arg1)
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x)
   at Fable.Fable2Babel.Util.transformApply(IBabelCompiler com, Context ctx, Expr callee, FSharpList`1 args, ApplyKind kind, FSharpOption`1 range)
   at Fable.Fable2Babel.Util.buildArray@244.Invoke(Expr x)
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x)
   at Fable.Fable2Babel.Util.buildArray(IBabelCompiler com, Context ctx, ArrayConsKind consKind, Type typ)
   at Fable.Fable2Babel.Util.transformObjectExpr@429.Invoke(Declaration _arg1)
   at Microsoft.FSharp.Primitives.Basics.List.choose[T,TResult](FSharpFunc`2 f, FSharpList`1 xs)
   at Fable.Fable2Babel.Util.transformObjectExpr(IBabelCompiler com, Context ctx, FSharpList`1 members, FSharpList`1 interfaces, FSharpOption`1 baseClass, FSharpOption`1 range)
   at Fable.Fable2Babel.Util.transformExpr(IBabelCompiler com, Context ctx, Expr expr)
   at Fable.Fable2Babel.Util.transformFunction[a](IBabelCompiler com, Context ctx, FSharpList`1 args, Expr body)
   at Fable.Fable2Babel.Util.makeCompiler@1024.Fable-Fable2Babel-IBabelCompiler-TransformFunction(Context , FSharpList`1 , Expr )
   at Fable.Fable2Babel.Util.getMemberArgs(IBabelCompiler com, Context ctx, FSharpList`1 args, Expr body, FSharpList`1 typeParams, Boolean hasRestParams)
   at Fable.Fable2Babel.Util.declareMethod@792(IBabelCompiler com, Context ctx, SourceLocation range, ClassMethodKind kind, String name, FSharpList`1 args, Expr body, FSharpList`1 typeParams, Boolean hasRestParams, Boolean isStatic, Boolean isSymbol)
   at Fable.Fable2Babel.Util.transformClass$cont@808(IBabelCompiler com, Context ctx, FSharpOption`1 ent, Declaration _arg1, Unit unitVar)
   at Fable.Fable2Babel.Util.transformClass@806.Invoke(Declaration _arg1)
   at Microsoft.FSharp.Primitives.Basics.List.mapToFreshConsTail[a,b](FSharpList`1 cons, FSharpFunc`2 f, FSharpList`1 x)
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x)
   at Fable.Fable2Babel.Util.transformClass(IBabelCompiler com, Context ctx, FSharpOption`1 range, FSharpOption`1 ent, FSharpOption`1 baseClass, FSharpList`1 decls)
   at Fable.Fable2Babel.Util.declareClass[a,b,c,d](IBabelCompiler com, Context ctx, FSharpFunc`2 declareMember, b modIdent, Entity ent, a privateName, FSharpList`1 entDecls, SourceLocation entRange, FSharpOption`1 baseClass, d isClass)
   at Fable.Fable2Babel.Util.transformModDecls@979.Invoke(FSharpList`1 acc, Declaration decl)
   at Microsoft.FSharp.Collections.ListModule.loop@219-29[T,TState](FSharpFunc`3 f, TState s, FSharpList`1 xs)
   at Fable.Fable2Babel.Util.transformModDecls[a](IBabelCompiler com, Context ctx, FSharpFunc`2 declareMember, FSharpOption`1 modIdent, FSharpList`1 decls)
   at Fable.Fable2Babel.Compiler.transformFiles@1105-4.Invoke(File file)"}
```

**Comment by alfonsogarciacaro** [comment]
This is again similar to #503, so I've added a [catch-all](https://github.com/fable-compiler/Fable/blob/f41fe87d64561f1e1a3b01de176b770e5f9eedaa/src/fable/Fable.Compiler/Replacements.fs#L1699-L1702) to prevent these issues happening with BCL and FSharp.Core :+1: Can you please try upgrading to latest compiler and core versions?

**Comment by ncave** [comment]
@alfonsogarciacaro Thanks, the catch-all works great.
