### ISSUE TITLE
Struct runtime error

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#568]
This compiles but results in a runtime error:
```
[<Struct>]
type Test<'T> = 
    new (f: unit -> 'T) = { func = f }
    val func : unit -> 'T
    member x.Value = x.func()


[<EntryPoint>]
let main argv =
    let f() = "5"
    let test = Test<_>(f)
    printfn "%A" test.Value
    0
```
Here is the error:
```
[ERROR] C:\Projects\test\src\test\out\project.js:18
class Test extends _Util.Any {
                        ^

TypeError: Class extends value #<NonDeclaredType> is not a constructor or null
    at Object.<anonymous> (C:\Projects\test\src\test\out\project.js:18:25)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

```
tested with fable-compiler: v0.7.11 / fable-core: v0.7.10

**Comment by alfonsogarciacaro** [comment]
Thanks for the report! I wasn't taking structs into account so far 😅 For now, it seems they can be just compiled as records (the constructor becomes a static method, but that can be optimized lated). Can you please try with fable-compiler 0.7.12?

**Comment by ncave** [comment]
Thanks, it works!

**Comment by ncave** [comment]
@alfonsogarciacaro Thanks, it works, but [this commit](https://github.com/fable-compiler/Fable/commit/cfd55e1f759f636aca95ac3f4bfa51dd9b217437#diff-44519f4796af2d6ca3cd9c83a7fa94df) breaks the tests so I can't publish.
Did you publish 0.7.14 without it?

For some reason this generates an extra constructor:
```
[<Struct>]
type ValueType2<'T>(i: int, j: int) =
    member x.Value = i + j
```
Runtime error:
```
cmd /C npm run test --

> fable-tests@0.1.0 test C:\Projects\Fable\build\tests
> mocha Main

C:\Projects\Fable\build\tests\Main\TypeTests.js:972
    constructor(i, j) {
    ^^^^^^^^^^^
SyntaxError: A class may only have one constructor
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at C:\Projects\Fable\build\tests\node_modules\mocha\lib\mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (C:\Projects\Fable\build\tests\node_modules\mocha\lib\mocha.js:219:14)
    at Mocha.run (C:\Projects\Fable\build\tests\node_modules\mocha\lib\mocha.js:487:10)
    at Object.<anonymous> (C:\Projects\Fable\build\tests\node_modules\mocha\bin\_mocha:459:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

**Comment by alfonsogarciacaro** [comment]
This is what happens when you confidently add a test and then go to bed ;) I decided to compile structs as if they were records, and Fable automatically adds a compiler for records. Now I added a check before implementing a default constructor, could you please try with 0.7.15?

**Comment by ncave** [comment]
That works, thanks!
