### ISSUE TITLE
Circular dependency support

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#569]
Are circular dependencies supported? This compiles fine:
```
type Employee = { name: string; age: float; location: Location }
and Location = { name: string; mutable employees: Employee list }

[<EntryPoint>]
let main argv =
    let location = { name="NY"; employees=[] }
    let alice = { name="Alice"; age=20.0; location=location  }
    let bob = { name="Bob"; age=30.0; location=location }
    0
```
but produces the following runtime error:
```
[ERROR] C:\Projects\test\src\test\out\project.js:34
        location: Location
                  ^

ReferenceError: Location is not defined
    at [reflection] (C:\Projects\test\src\test\out\project.js:34:19)
    at declare (C:\Projects\test\src\test\node_modules\fable-core\umd\Util.js:181:24)
    at Object.<anonymous> (C:\Projects\test\src\test\out\project.js:50:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
```

**Comment by alfonsogarciacaro** [comment]
Argh, this is caused because I put all the reflection info (type name, interfaces, properties) in a single method which is called when declaring the type (to add the name to a global dictionary), but because the properties make a reference to the (still to be declared) type, everything falls apart.

I changed the way to declare the types so the name is used directly. Can you please try with latest fable-compiler? (You also need to update fable-core)

**Comment by ncave** [comment]
Thanks, it works, but the commit after that breaks the tests so I can't publish:
```
cmd /C npm run test --

> fable-tests@0.1.0 test C:\Projects\Fable\build\tests
> mocha Main

C:\Projects\Fable\build\tests\Main\TypeTests.js:972
    constructor(i, j) {
    ^^^^^^^^^^^
SyntaxError: A class may only have one constructor
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at C:\Projects\Fable\build\tests\node_modules\mocha\lib\mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (C:\Projects\Fable\build\tests\node_modules\mocha\lib\mocha.js:219:14)
    at Mocha.run (C:\Projects\Fable\build\tests\node_modules\mocha\lib\mocha.js:487:10)
    at Object.<anonymous> (C:\Projects\Fable\build\tests\node_modules\mocha\bin\_mocha:459:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```
