### ISSUE TITLE
Fable build is broken after fresh repo cloning

### ISSUE THREAD

**Issue by irium** [fable-compiler/Fable#596]
### Description

After cloning Fable repo and running `build.cmd` build is exited with error.

### Repro steps

1. Clone Fable repo.

2. Open shell from repo directory.

3. Run `build.cmd`.

### Expected behavior

Build completed successfully.

### Actual behavior

```
CWD: build/fable-core
cmd /C npm run babel -- . --out-dir umd

> fable-core@0.7.15 babel C:\src\Fable\build\fable-core
> babel "." "--out-dir" "umd"

Array.js -> umd\Array.js
Assert.js -> umd\Assert.js
Async.js -> umd\Async.js
AsyncBuilder.js -> umd\AsyncBuilder.js
Choice.js -> umd\Choice.js
Date.js -> umd\Date.js
Event.js -> umd\Event.js
GenericComparer.js -> umd\GenericComparer.js
Lazy.js -> umd\Lazy.js
List.js -> umd\List.js
ListClass.js -> umd\ListClass.js
MailboxProcessor.js -> umd\MailboxProcessor.js
Map.js -> umd\Map.js
ReferenceError: Unknown plugin "transform-runtime" specified in "C:\\src\\Fable\\build\\fable-core\\node_modules\\regenerator-transform\\package.json" at 0, attempted to resolve relative to "C:\\src\\Fable\\build\\fable-core\\node_modules\\regenerator-transform"
    at C:\src\Fable\build\fable-core\node_modules\babel-core\lib\transformation\file\options\option-manager.js:176:17
    at Array.map (native)
    at Function.normalisePlugins (C:\src\Fable\build\fable-core\node_modules\babel-core\lib\transformation\file\options\option-manager.js:154:20)
    at OptionManager.mergeOptions (C:\src\Fable\build\fable-core\node_modules\babel-core\lib\transformation\file\options\option-manager.js:229:36)
    at OptionManager.init (C:\src\Fable\build\fable-core\node_modules\babel-core\lib\transformation\file\options\option-manager.js:374:12)
    at File.initOptions (C:\src\Fable\build\fable-core\node_modules\babel-core\lib\transformation\file\index.js:216:65)
    at new File (C:\src\Fable\build\fable-core\node_modules\babel-core\lib\transformation\file\index.js:139:24)
    at Pipeline.transform (C:\src\Fable\build\fable-core\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transform (C:\src\Fable\build\fable-core\node_modules\babel-cli\lib\babel\util.js:50:22)
    at Object.compile (C:\src\Fable\build\fable-core\node_modules\babel-cli\lib\babel\util.js:59:12)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\irium_000\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "babel" "--" "." "--out-dir" "umd"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE
npm ERR! fable-core@0.7.15 babel: `babel "." "--out-dir" "umd"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fable-core@0.7.15 babel script 'babel "." "--out-dir" "umd"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fable-core package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel "." "--out-dir" "umd"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fable-core
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fable-core
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\src\Fable\build\fable-core\npm-debug.log```

### Known workarounds

### Related information 

* Fable Version
`master` branch at 37dd2c4f8d978a5ee3825ec6b760858a021a4bb6
* .NET 4.5 
* Windows 10 Pro

**Comment by alfonsogarciacaro** [comment]
This should be fixed in latest master :+1:
