### ISSUE TITLE
 Fable 1.x: "Cannot compile expression" (F# 4.1 Result type)

### ISSUE THREAD

**Issue by et1975** [fable-compiler/Fable#773]
### Description

Fable elmish react/navigation sample fails to compile with new parser.
This is [the sample](https://github.com/fable-compiler/fable-elmish/tree/master/samples/react/navigation) and this is [the code](https://github.com/fable-compiler/fable-elmish/blob/master/src/elmish-browser/parser.fs#L54) it seems to be having difficulty with.

### Error
```
ERROR: Cannot compile expression in (L54,18-L54,40): AddressOf Value val matchValue (/Users/eugene.tolmachev/sources/fable-elmish/samples/react/node_modules/fable-elmish-browser/parser.fs)
   at Fable.FSharp2Fable.Compiler.transformExpr@768-34.Invoke(String message)
   at Fable.FSharp2Fable.Compiler.transformExpr(IFableCompiler com, Context ctx, FSharpExpr fsExpr)
   at Fable.FSharp2Fable.Compiler.transformExpr(IFableCompiler com, Context ctx, FSharpExpr fsExpr)
   at Fable.FSharp2Fable.Compiler.transformExpr(IFableCompiler com, Context ctx, FSharpExpr fsExpr)
   at Fable.FSharp2Fable.Compiler.transformExpr(IFableCompiler com, Context ctx, FSharpExpr fsExpr)
   at Fable.FSharp2Fable.Compiler.transformExpr(IFableCompiler com, Context ctx, FSharpExpr fsExpr)
   at Fable.FSharp2Fable.Compiler.transformExpr(IFableCompiler com, Context ctx, FSharpExpr fsExpr)
   at Fable.FSharp2Fable.Compiler.transformExpr(IFableCompiler com, Context ctx, FSharpExpr fsExpr)
   at Fable.FSharp2Fable.Compiler.transformExpr(IFableCompiler com, Context ctx, FSharpExpr fsExpr)
   at Fable.FSharp2Fable.Compiler.addMethod@945(IFableCompiler com, Context ctx, DeclInfo declInfo, SourceLocation range, FSharpOption`1 import, FSharpMemberOrFunctionOrValue meth, FSharpList`1 args, FSharpExpr body)
   at Fable.FSharp2Fable.Compiler.transformMemberDecl(IFableCompiler com, Context ctx, DeclInfo declInfo, FSharpMemberOrFunctionOrValue meth, FSharpList`1 args, FSharpExpr body)
   at Microsoft.FSharp.Collections.ListModule.loop@219-29[T,TState](FSharpFunc`3 f, TState s, FSharpList`1 xs)
   at Fable.FSharp2Fable.Compiler.transformDeclarations(IFableCompiler com, Context ctx, FSharpList`1 decls)
   at Fable.FSharp2Fable.Compiler.transformFile(ICompiler com, ICompilerState state, FSharpCheckProjectResults checkedProject, String fileName)
```

Please provide the expected and actual results.

### Related information 

* fable-compiler version: 1.x
* fable-core version: ??
* Operating system: OSX

**Comment by alfonsogarciacaro** [comment]
This actually happens because we're missing support for the F# 4.1 Result type, related to #770

**Comment by et1975** [comment]
I think we can close this now.
