### ISSUE TITLE
[ERROR] unhandled construct in AST

### ISSUE THREAD

**Issue by Pauan** [fable-compiler/Fable#816]
### Repro code

```fsharp
module Main

type Foo =
    | Foo of Result<int, string>

let foo (a: Foo): bool =
    match a with
    | Foo(Ok(_)) -> true
    | _ -> false

printfn "%A" (foo <| Foo(Ok(1)))
```

### Description

When running the repro code, I get this error:

```
ERROR: unhandled construct in AST at /home/pauan/Programming/fsharp/fable-getting-started/src/fs/Main.fs (7,10--7,11) IsSynthetic=false (/home/pauan/Programming/fsharp/fable-getting-started/src/fs/Main.fs)
   at Microsoft.FSharp.Compiler.SourceCodeServices.ExprTranslationImpl.wfail[a](String msg, range m)
   at Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExprConvert.ConvExprPrim(cenv cenv, ExprTranslationEnv env, Expr expr)
   at Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExprConvert.ConvDecisionTreePrim@980.Invoke(DecisionTreeCase _arg2, E acc)
   at Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExprConvert.ConvExprPrimLinear(cenv cenv, ExprTranslationEnv env, Expr expr, FSharpFunc`2 contf)
   at Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExprConvert.ConvExprOnDemand@1036.Invoke(Unit unitVar0)
   at Microsoft.FSharp.Compiler.SourceCodeServices.FSharpExpr.get_E()
   at Microsoft.FSharp.Compiler.SourceCodeServices.BasicPatterns.|ILFieldGet|_|(FSharpExpr e)
   at Fable.FSharp2Fable.Compiler.|SpecialValue|_|(IFableCompiler com, Context ctx, FSharpExpr _arg1)
   at Fable.FSharp2Fable.Compiler.transformExpr(IFableCompiler com, Context ctx, FSharpExpr fsExpr)
   at Fable.FSharp2Fable.Compiler.addMethod@950(IFableCompiler com, Context ctx, DeclInfo declInfo, SourceLocation range, FSharpOption`1 import, FSharpMemberOrFunctionOrValue meth, FSharpList`1 args, FSharpExpr body)
   at Fable.FSharp2Fable.Compiler.transformMemberDecl(IFableCompiler com, Context ctx, DeclInfo declInfo, FSharpMemberOrFunctionOrValue meth, FSharpList`1 args, FSharpExpr body)
   at Microsoft.FSharp.Collections.ListModule.loop@219-29[T,TState](FSharpFunc`3 f, TState s, FSharpList`1 xs)
   at Fable.FSharp2Fable.Compiler.transformDeclarations(IFableCompiler com, Context ctx, FSharpList`1 decls)
   at Fable.FSharp2Fable.Compiler.transformFile(ICompiler com, ICompilerState state, FSharpCheckProjectResults checkedProject, String fileName)
```

It works fine in `fsharpi`

### Related information 

* fable-compiler version: 1.0.0-narumi-909
* fable-core version: 1.0.0-narumi-909
* Operating system: Debian GNU/Linux Testing (64-bit)

**Comment by alfonsogarciacaro** [comment]
Thanks for reporting. This is the first time I see this 😮 I need to check if the problem comes from Fable or from FSharp.Compiler.Service.

**Comment by Pauan** [comment]
Yeah, it's super weird. I was only able to reproduce it with `Result`, it didn't error with a regular discriminated union.

**Comment by Pauan** [comment]
Thanks! :heart: Now I can get `fable-unit-test` working.
