### ISSUE TITLE
Cannot assign to a mutable value that exists in a module defined in a different file

### ISSUE THREAD

**Issue by chadunit** [fable-compiler/Fable#986]
### Description

Attempting to assign to a mutable value that exists in a module defined in a different file results in compile error.

### Repro code

Using the standard ```dotnew new fable``` template, add the file DifferentFile.fs and include it in the fsproj compile group, and update App.fs as follows.
 
DifferentFile.fs:
```
namespace N

module DifferentFile =
  let mutable differentMutableValue = 1
```

App.fs:
```
namespace N

module SameFile =
  let mutable mutableValue = 1

module App =
  SameFile.mutableValue <- 2 // this line works
  DifferentFile.differentMutableValue <- 2 // this line fails to compile
```

### Expected and actual results

```
ERROR in ./src/App.fs
Module build failed: SyntaxError: unknown: "differentMutableValue" is read-only (This is an error on an internal node. Probably an internal error)
    at File.buildCodeFrameError (C:\src\fablemodtest\node_modules\babel-core\lib\transformation\file\index.js:427:15)
    at NodePath.buildCodeFrameError (C:\src\fablemodtest\node_modules\babel-traverse\lib\path\index.js:140:26)
    at PluginPass.Scope (C:\src\fablemodtest\node_modules\babel-plugin-check-es2015-constants\lib\index.js:35:29)
    at PluginPass.newFn (C:\src\fablemodtest\node_modules\babel-traverse\lib\visitors.js:318:17)
    at newFn (C:\src\fablemodtest\node_modules\babel-traverse\lib\visitors.js:276:21)
    at NodePath._call (C:\src\fablemodtest\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (C:\src\fablemodtest\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (C:\src\fablemodtest\node_modules\babel-traverse\lib\path\context.js:105:12)
    at TraversalContext.visitQueue (C:\src\fablemodtest\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (C:\src\fablemodtest\node_modules\babel-traverse\lib\context.js:108:19)
 @ ./fablemodtest.fsproj 1:0-29
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./fablemodtest.fsproj
```
### Related information 

* fable-core version: 1.0.8
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
Hi @chadunit, thanks a lot for the report! This is a tricky issue that it's related to how ES2015 modules work and has surfaced now as we don't use commonjs modules anymore. It can (and should) be fixed but if you need a quick around now, you can force `DifferentFile` to be a nested module which doesn't have this problem. By default, Fable tries to compile files with a single module as if they were ES2015 modules (which have the benefit of tree shaking when bundling), but you can force it to be a nested module by putting something in the outer namespace:

```fsharp
namespace N

type IDummy = interface end

module DifferentFile =
  let mutable differentMutableValue = 1
```
